% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={ejercicios-tema-8},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{ejercicios-tema-8}
\author{}
\date{\vspace{-2.5em}}

\begin{document}
\maketitle

Introducción

Este trabajo pretende aplicar el uso del análisis bayesiano a la teoría
de respuesta al ítem. Para realizar esta aplicación, se utilizan las
respuestas a ítems del test PISA 2000. Los ítems de esta prueba evalúan
la comprensión lectora a través de diversos formatos y grados de
dificultad. El enfoque de la TRI será el modelo de Rash o de 1PL y
mediante este se estimarán parámetros de dificultad por ítem y nivel de
habilidad de cada estudiante. Sin embargo, en lugar de estimar un valor
puntual por parámetro, estimaré una distribución posterior. Además, para
evaluar el ajuste del modelo, utilizaré comprobaciones predictivas
posteriores.

Por tanto, para estimar la theta y dificultad, se utilizará el paquete
brms de R que implementará métodos de muestreo de Markov Chain Monte
Carlo para obtener distribuciones posteriores. Este método permitirá
obtener incertidumbre mediante intervalos creíbles.

Las distribuciones previas utilizadas son debilesmente informativas:para
las habilidades de los estudiantes:𝜃∼𝑁(0,1). Para las dificultades de
los ítems: bj∼N(0,2). El modelo se estimará con 4 cadenas de meustreo,
2000 iteraciones por cadenas (1000 coomo warm-up), resultando en 4000
muestras posteriores del parámetro.

Las posterior predictive checks se utizarán para comparar las respuestas
observadas con datos simulados a partir de la distribución posterior,
para ver hasta qué punto el modelo es capaz de reproducir los patrones
reales del conjunto de datos.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Cargar paquetes necesarios}

\FunctionTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## -- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --
## v dplyr     1.1.4     v readr     2.1.5
## v forcats   1.0.0     v stringr   1.5.1
## v ggplot2   3.5.1     v tibble    3.2.1
## v lubridate 1.9.4     v tidyr     1.3.1
## v purrr     1.0.4     
## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
## i Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(dplyr)}
\FunctionTok{library}\NormalTok{(readr)}

\CommentTok{\# Leer CSV con separador punto y coma}
\NormalTok{pisa }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv2}\NormalTok{(}\StringTok{"\textasciitilde{}/Documents/Máster Metodología de las ciencias del comportamiento y de la salud/Análisis Bayesiano/tema 8/tarea final/datos/PISA\_2000 (2).csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## i Using "','" as decimal and "'.'" as grouping mark. Use `read_delim()` for more control.
## Rows: 1095 Columns: 30-- Column specification --------------------------------------------------------
## Delimiter: ";"
## dbl (30): idstud, female, HISEI, AGE, R040Q02, R040Q03A, R040Q03B, R040Q04, ...
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Seleccionar ítems (todos empiezan con "R")}
\NormalTok{items }\OtherTok{\textless{}{-}}\NormalTok{ pisa }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(}\FunctionTok{starts\_with}\NormalTok{(}\StringTok{"R"}\NormalTok{))}

\CommentTok{\# Verificar qué ítems tienen el valor 2}
\NormalTok{valores\_por\_item }\OtherTok{\textless{}{-}} \FunctionTok{map}\NormalTok{(items, }\SpecialCharTok{\textasciitilde{}} \FunctionTok{unique}\NormalTok{(.x))}
\NormalTok{items\_con\_2 }\OtherTok{\textless{}{-}} \FunctionTok{names}\NormalTok{(}\FunctionTok{keep}\NormalTok{(valores\_por\_item, }\SpecialCharTok{\textasciitilde{}} \DecValTok{2} \SpecialCharTok{\%in\%}\NormalTok{ .x))}
\NormalTok{items\_solo\_01 }\OtherTok{\textless{}{-}} \FunctionTok{setdiff}\NormalTok{(}\FunctionTok{names}\NormalTok{(items), items\_con\_2)}

\CommentTok{\# Recodificar: ítems con 2 → 2 = 1 (correcto); 0 y 1 = 0 (incorrecto/parcial)}
\CommentTok{\#              ítems con solo 0 y 1 → 1 = 1 (correcto); 0 = 0}
\NormalTok{items\_binarios }\OtherTok{\textless{}{-}}\NormalTok{ items }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\FunctionTok{across}\NormalTok{(}\FunctionTok{all\_of}\NormalTok{(items\_con\_2), }\SpecialCharTok{\textasciitilde{}} \FunctionTok{ifelse}\NormalTok{(. }\SpecialCharTok{==} \DecValTok{2}\NormalTok{, }\DecValTok{1}\NormalTok{,}
                                       \FunctionTok{ifelse}\NormalTok{(. }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{), }\DecValTok{0}\NormalTok{, }\ConstantTok{NA}\NormalTok{)))) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\FunctionTok{across}\NormalTok{(}\FunctionTok{all\_of}\NormalTok{(items\_solo\_01), }\SpecialCharTok{\textasciitilde{}} \FunctionTok{ifelse}\NormalTok{(. }\SpecialCharTok{==} \DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{,}
                                         \FunctionTok{ifelse}\NormalTok{(. }\SpecialCharTok{==} \DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{, }\ConstantTok{NA}\NormalTok{))))}

\CommentTok{\# Confirmar que hay 1s y 0s}
\FunctionTok{summary}\NormalTok{(items\_binarios)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     R040Q02          R040Q03A        R040Q03B         R040Q04      
##  Min.   :0.0000   Min.   :0.000   Min.   :0.0000   Min.   :0.0000  
##  1st Qu.:0.0000   1st Qu.:0.000   1st Qu.:0.0000   1st Qu.:0.0000  
##  Median :1.0000   Median :1.000   Median :0.0000   Median :1.0000  
##  Mean   :0.6091   Mean   :0.516   Mean   :0.3205   Mean   :0.7443  
##  3rd Qu.:1.0000   3rd Qu.:1.000   3rd Qu.:1.0000   3rd Qu.:1.0000  
##  Max.   :1.0000   Max.   :1.000   Max.   :1.0000   Max.   :1.0000  
##     R040Q06          R077Q02          R077Q03          R077Q04      
##  Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  
##  1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000  
##  Median :1.0000   Median :1.0000   Median :0.0000   Median :1.0000  
##  Mean   :0.5553   Mean   :0.7315   Mean   :0.4694   Mean   :0.5434  
##  3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000  
##  Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000  
##     R077Q05          R077Q06          R088Q01          R088Q03      
##  Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  
##  1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000  
##  Median :0.0000   Median :0.0000   Median :1.0000   Median :0.0000  
##  Mean   :0.2594   Mean   :0.4274   Mean   :0.6137   Mean   :0.2968  
##  3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000  
##  Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000  
##     R088Q04T        R088Q05T        R088Q07          R110Q01      
##  Min.   :0.000   Min.   :0.000   Min.   :0.0000   Min.   :0.0000  
##  1st Qu.:0.000   1st Qu.:0.000   1st Qu.:0.0000   1st Qu.:1.0000  
##  Median :0.000   Median :1.000   Median :1.0000   Median :1.0000  
##  Mean   :0.116   Mean   :0.632   Mean   :0.5543   Mean   :0.8009  
##  3rd Qu.:0.000   3rd Qu.:1.000   3rd Qu.:1.0000   3rd Qu.:1.0000  
##  Max.   :1.000   Max.   :1.000   Max.   :1.0000   Max.   :1.0000  
##     R110Q04          R110Q05          R110Q06          R216Q01      
##  Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  
##  1st Qu.:1.0000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000  
##  Median :1.0000   Median :1.0000   Median :1.0000   Median :1.0000  
##  Mean   :0.7909   Mean   :0.6557   Mean   :0.7114   Mean   :0.7105  
##  3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000  
##  Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000  
##     R216Q02          R216Q03T         R216Q04          R216Q06      
##  Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  
##  1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000  
##  Median :1.0000   Median :0.0000   Median :0.0000   Median :1.0000  
##  Mean   :0.5187   Mean   :0.3808   Mean   :0.3479   Mean   :0.6411  
##  3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000  
##  Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000  
##     R236Q01          R236Q02      
##  Min.   :0.0000   Min.   :0.0000  
##  1st Qu.:0.0000   1st Qu.:0.0000  
##  Median :0.0000   Median :0.0000  
##  Mean   :0.4502   Mean   :0.1991  
##  3rd Qu.:1.0000   3rd Qu.:0.0000  
##  Max.   :1.0000   Max.   :1.0000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#AHORA CALCULO EL MODELO 2PL}

\CommentTok{\#PREPARAR EL ENTORNO}

\FunctionTok{library}\NormalTok{(brms)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: Rcpp
## Loading 'brms' package (version 2.22.0). Useful instructions
## can be found by typing help('brms'). A more detailed introduction
## to the package is available through vignette('brms_overview').
## 
## Attaching package: 'brms'
## 
## The following object is masked from 'package:stats':
## 
##     ar
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#TRANSFORMAR A FORMATO LARGO}

\CommentTok{\# Agregar identificador de estudiante}
\NormalTok{items\_binarios}\SpecialCharTok{$}\NormalTok{id }\OtherTok{\textless{}{-}} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{nrow}\NormalTok{(items\_binarios)}

\CommentTok{\# Transformar a formato largo}
\NormalTok{data\_long }\OtherTok{\textless{}{-}}\NormalTok{ items\_binarios }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{pivot\_longer}\NormalTok{(}
    \AttributeTok{cols =} \SpecialCharTok{{-}}\NormalTok{id,}
    \AttributeTok{names\_to =} \StringTok{"item"}\NormalTok{,}
    \AttributeTok{values\_to =} \StringTok{"response"}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{drop\_na}\NormalTok{()  }\CommentTok{\# Eliminar NA (no respuesta)}

\CommentTok{\# Modelo logístico con efectos aleatorios por ítem (dificultad) y por persona (habilidad)}
\NormalTok{modelo\_2pl }\OtherTok{\textless{}{-}} \FunctionTok{brm}\NormalTok{(}
\NormalTok{  response }\SpecialCharTok{\textasciitilde{}} \DecValTok{1} \SpecialCharTok{+}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{|}\NormalTok{ id) }\SpecialCharTok{+}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{|}\NormalTok{ item),  }\CommentTok{\# Rasgo latente por persona, dificultad por ítem}
  \AttributeTok{data =}\NormalTok{ data\_long,}
  \AttributeTok{family =} \FunctionTok{bernoulli}\NormalTok{(}\AttributeTok{link =} \StringTok{"logit"}\NormalTok{),}
  \AttributeTok{iter =} \DecValTok{2000}\NormalTok{,}
  \AttributeTok{chains =} \DecValTok{4}\NormalTok{,}
  \AttributeTok{cores =} \DecValTok{4}\NormalTok{,}
  \AttributeTok{seed =} \DecValTok{123}\NormalTok{,}
  \AttributeTok{control =} \FunctionTok{list}\NormalTok{(}\AttributeTok{adapt\_delta =} \FloatTok{0.95}\NormalTok{)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Compiling Stan program...
## Start sampling
\end{verbatim}

\begin{verbatim}
## Warning: Bulk Effective Samples Size (ESS) is too low, indicating posterior means and medians may be unreliable.
## Running the chains for more iterations may help. See
## https://mc-stan.org/misc/warnings.html#bulk-ess
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Resumen de parámetros estimados}
\FunctionTok{summary}\NormalTok{(modelo\_2pl)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Family: bernoulli 
##   Links: mu = logit 
## Formula: response ~ 1 + (1 | id) + (1 | item) 
##    Data: data_long (Number of observations: 28470) 
##   Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
##          total post-warmup draws = 4000
## 
## Multilevel Hyperparameters:
## ~id (Number of levels: 1095) 
##               Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## sd(Intercept)     1.29      0.04     1.23     1.37 1.00      952     1965
## 
## ~item (Number of levels: 26) 
##               Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## sd(Intercept)     1.16      0.18     0.89     1.58 1.00      721     1149
## 
## Regression Coefficients:
##           Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## Intercept     0.11      0.22    -0.32     0.57 1.01      240      709
## 
## Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
## and Tail_ESS are effective sample size measures, and Rhat is the potential
## scale reduction factor on split chains (at convergence, Rhat = 1).
## Warmup)
## Chain 3: Iteration:    1 / 2000 [  0%]  (Warmup)
## Chain 4: Iteration:    1 / 2000 [  0%]  (Warmup)
## Chain 4: Iteration:  200 / 2000 [ 10%]  (Warmup)
## Chain 2: Iteration:  200 / 2000 [ 10%]  (Warmup)
## Chain 3: Iteration:  200 / 2000 [ 10%]  (Warmup)
## Chain 1: Iteration:  200 / 2000 [ 10%]  (Warmup)
## Chain 2: Iteration:  400 / 2000 [ 20%]  (Warmup)
## Chain 4: Iteration:  400 / 2000 [ 20%]  (Warmup)
## Chain 1: Iteration:  400 / 2000 [ 20%]  (Warmup)
## Chain 3: Iteration:  400 / 2000 [ 20%]  (Warmup)
## Chain 2: Iteration:  600 / 2000 [ 30%]  (Warmup)
## Chain 1: Iteration:  600 / 2000 [ 30%]  (Warmup)
## Chain 4: Iteration:  600 / 2000 [ 30%]  (Warmup)
## Chain 2: Iteration:  800 / 2000 [ 40%]  (Warmup)
## Chain 3: Iteration:  600 / 2000 [ 30%]  (Warmup)
## Chain 4: Iteration:  800 / 2000 [ 40%]  (Warmup)
## Chain 1: Iteration:  800 / 2000 [ 40%]  (Warmup)
## Chain 2: Iteration: 1000 / 2000 [ 50%]  (Warmup)
## Chain 3: Iteration:  800 / 2000 [ 40%]  (Warmup)
## Chain 2: Iteration: 1001 / 2000 [ 50%]  (Sampling)
## Chain 4: Iteration: 1000 / 2000 [ 50%]  (Warmup)
## Chain 4: Iteration: 1001 / 2000 [ 50%]  (Sampling)
## Chain 1: Iteration: 1000 / 2000 [ 50%]  (Warmup)
## Chain 1: Iteration: 1001 / 2000 [ 50%]  (Sampling)
## Chain 2: Iteration: 1200 / 2000 [ 60%]  (Sampling)
## Chain 3: Iteration: 1000 / 2000 [ 50%]  (Warmup)
## Chain 3: Iteration: 1001 / 2000 [ 50%]  (Sampling)
## Chain 4: Iteration: 1200 / 2000 [ 60%]  (Sampling)
## Chain 2: Iteration: 1400 / 2000 [ 70%]  (Sampling)
## Chain 4: Iteration: 1400 / 2000 [ 70%]  (Sampling)
## Chain 1: Iteration: 1200 / 2000 [ 60%]  (Sampling)
## Chain 2: Iteration: 1600 / 2000 [ 80%]  (Sampling)
## Chain 3: Iteration: 1200 / 2000 [ 60%]  (Sampling)
## Chain 4: Iteration: 1600 / 2000 [ 80%]  (Sampling)
## Chain 2: Iteration: 1800 / 2000 [ 90%]  (Sampling)
## Chain 1: Iteration: 1400 / 2000 [ 70%]  (Sampling)
## Chain 4: Iteration: 1800 / 2000 [ 90%]  (Sampling)
## Chain 2: Iteration: 2000 / 2000 [100%]  (Sampling)
## Chain 2: 
## Chain 2:  Elapsed Time: 405.124 seconds (Warm-up)
## Chain 2:                323.412 seconds (Sampling)
## Chain 2:                728.536 seconds (Total)
## Chain 2: 
## Chain 3: Iteration: 1400 / 2000 [ 70%]  (Sampling)
## Chain 4: Iteration: 2000 / 2000 [100%]  (Sampling)
## Chain 4: 
## Chain 4:  Elapsed Time: 453.753 seconds (Warm-up)
## Chain 4:                326.241 seconds (Sampling)
## Chain 4:                779.994 seconds (Total)
## Chain 4: 
## Chain 1: Iteration: 1600 / 2000 [ 80%]  (Sampling)
## Chain 3: Iteration: 1600 / 2000 [ 80%]  (Sampling)
## Chain 1: Iteration: 1800 / 2000 [ 90%]  (Sampling)
## Chain 3: Iteration: 1800 / 2000 [ 90%]  (Sampling)
## Chain 1: Iteration: 2000 / 2000 [100%]  (Sampling)
## Chain 1: 
## Chain 1:  Elapsed Time: 461.402 seconds (Warm-up)
## Chain 1:                527.631 seconds (Sampling)
## Chain 1:                989.033 seconds (Total)
## Chain 1: 
## Chain 3: Iteration: 2000 / 2000 [100%]  (Sampling)
## Chain 3: 
## Chain 3:  Elapsed Time: 486.005 seconds (Warm-up)
## Chain 3:                517.587 seconds (Sampling)
## Chain 3:                1003.59 seconds (Total)
## Chain 3:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Graficar distribuciones posteriores}
\FunctionTok{plot}\NormalTok{(modelo\_2pl)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Sin-título_files/figure-latex/unnamed-chunk-1-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Efectos por ítem (dificultad)}
\FunctionTok{ranef}\NormalTok{(modelo\_2pl)}\SpecialCharTok{$}\NormalTok{item}

\CommentTok{\# Efectos por persona (habilidad)}
\FunctionTok{ranef}\NormalTok{(modelo\_2pl)}\SpecialCharTok{$}\NormalTok{id}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  1.703422e+00
## 28   -1.65385044 0.4899520 -2.66579016 -7.168799e-01
## 29   -3.21247761 0.7003048 -4.67463542 -1.948572e+00
## 30   -0.65843802 0.4317276 -1.50703104  1.948876e-01
## 31   -1.42368131 0.4591812 -2.37110155 -5.864620e-01
## 32    1.00227554 0.4465372  0.13393953  1.909205e+00
## 33    0.80432879 0.4603658 -0.11440689  1.749442e+00
## 34    0.04614834 0.4194619 -0.75879954  8.537401e-01
## 35   -0.12340033 0.4153132 -0.93302790  6.796784e-01
## 36   -0.29774799 0.4203024 -1.15635530  5.231492e-01
## 37   -0.30852776 0.4077410 -1.11558789  4.855212e-01
## 38   -0.65430928 0.4159795 -1.47328424  1.786440e-01
## 39   -1.02459581 0.4522035 -1.95135712 -1.726460e-01
## 40   -1.88603947 0.4900127 -2.88081888 -1.007847e+00
## 41    0.41055304 0.4404759 -0.43908296  1.269304e+00
## 42    1.21855724 0.4878017  0.30596121  2.236524e+00
## 43   -0.66236499 0.4393818 -1.52134587  1.958813e-01
## 44    0.59298296 0.4473138 -0.28122511  1.490878e+00
## 45    0.40341051 0.4541479 -0.49021883  1.342844e+00
## 46   -0.65165280 0.4249912 -1.49324868  1.685907e-01
## 47    0.78521539 0.4509419 -0.09233873  1.679024e+00
## 48    1.44790864 0.4986261  0.51488035  2.437545e+00
## 49   -0.83746562 0.4331456 -1.69894687 -5.734727e-03
## 50    0.22820910 0.4342985 -0.63294630  1.060598e+00
## 51    0.78992238 0.4423881 -0.04929347  1.701282e+00
## 52    0.05220502 0.4262297 -0.75277602  8.738243e-01
## 53    0.99367873 0.4623063  0.11743442  1.919038e+00
## 54    1.00215106 0.4576585  0.11872163  1.929961e+00
## 55   -0.11568862 0.4201295 -0.92985888  7.161324e-01
## 56    0.03699739 0.4243272 -0.76871808  8.599109e-01
## 57    1.00349158 0.4838729  0.09165942  1.987736e+00
## 58   -1.02437003 0.4539450 -1.91941877 -1.744107e-01
## 59    1.70204946 0.5059644  0.75417667  2.752921e+00
## 60   -0.66871249 0.4291020 -1.53502536  1.506070e-01
## 61    1.00287442 0.4646856  0.09336913  1.962101e+00
## 62   -1.21962659 0.4397611 -2.08787046 -3.754921e-01
## 63    1.21581588 0.4734052  0.31501589  2.193275e+00
## 64    1.98207814 0.5423483  0.97188996  3.086898e+00
## 65   -0.29429690 0.3990963 -1.07085873  4.835022e-01
## 66    1.69135528 0.5197306  0.70324468  2.770078e+00
## 67    1.44504711 0.4761823  0.53419311  2.440832e+00
## 68    0.78537732 0.4466134 -0.09364461  1.660584e+00
## 69    1.43839040 0.4776721  0.52288983  2.414435e+00
## 70    0.23086273 0.4225722 -0.56381179  1.066505e+00
## 71    1.21152301 0.4775468  0.31017406  2.129678e+00
## 72    1.98028632 0.5229589  1.00842603  3.046857e+00
## 73    0.99230983 0.4543548  0.13034957  1.919649e+00
## 74    1.70600355 0.5207213  0.73371498  2.771457e+00
## 75    0.05064183 0.4056453 -0.74315926  8.671438e-01
## 76    0.79278959 0.4506246 -0.06380665  1.689358e+00
## 77    1.21848580 0.4680189  0.32368651  2.132842e+00
## 78    1.44226434 0.4999891  0.50345762  2.437046e+00
## 79    0.21761245 0.4181940 -0.57191621  1.051246e+00
## 80   -0.13579929 0.4073338 -0.93382523  6.870576e-01
## 81   -1.02242934 0.4330169 -1.89484698 -2.119394e-01
## 82   -0.29884707 0.4081656 -1.06919413  4.903551e-01
## 83   -0.11809123 0.4217334 -0.94710904  7.186530e-01
## 84    0.60591426 0.4412265 -0.25011239  1.499342e+00
## 85   -0.11467473 0.4257750 -0.93796903  7.014667e-01
## 86   -0.30300746 0.4118821 -1.10322208  5.080479e-01
## 87    1.44812702 0.4871133  0.52963691  2.447665e+00
## 88    0.79317398 0.4479924 -0.07267946  1.698173e+00
## 89    0.59810349 0.4271726 -0.23415632  1.455195e+00
## 90    1.70588924 0.5341821  0.69388745  2.819217e+00
## 91    1.20329730 0.4821526  0.30737061  2.187148e+00
## 92    0.42282925 0.4255692 -0.38223241  1.282440e+00
## 93   -0.48444855 0.4264743 -1.34109737  3.429941e-01
## 94   -1.64392487 0.4753727 -2.62851598 -7.559445e-01
## 95   -0.29974984 0.4201137 -1.14299311  5.233975e-01
## 96    0.05055793 0.4173420 -0.76166541  8.757529e-01
## 97    0.59868031 0.4336287 -0.24025000  1.455397e+00
## 98    1.44304172 0.4766413  0.55759440  2.437784e+00
## 99    0.60444322 0.4443186 -0.25658356  1.498570e+00
## 100   1.21321347 0.4688873  0.32027468  2.152207e+00
## 101   0.99100839 0.4540981  0.12430290  1.908399e+00
## 102   0.79684914 0.4309382 -0.04208645  1.660758e+00
## 103   0.41079659 0.4387346 -0.42413428  1.304761e+00
## 104  -2.13697091 0.5246779 -3.21482189 -1.180437e+00
## 105  -1.03349870 0.4271068 -1.89557866 -1.926803e-01
## 106   0.79213339 0.4518752 -0.05245666  1.696866e+00
## 107  -1.22058534 0.4486071 -2.11995094 -3.525516e-01
## 108   1.44384508 0.4876400  0.53538288  2.447707e+00
## 109   0.59642631 0.4564594 -0.25735485  1.503971e+00
## 110   0.04855246 0.4250555 -0.76569047  9.100157e-01
## 111   0.41371928 0.4308007 -0.42010020  1.277449e+00
## 112   0.04975166 0.4278394 -0.79705130  9.160462e-01
## 113   1.45320886 0.4948144  0.52458919  2.430436e+00
## 114   0.59735010 0.4394640 -0.22191099  1.479974e+00
## 115   0.79178794 0.4473235 -0.07166005  1.707747e+00
## 116   1.44729858 0.4922981  0.50911949  2.434425e+00
## 117   1.22033391 0.4727966  0.33319099  2.174040e+00
## 118   1.20990419 0.4608299  0.34628791  2.148342e+00
## 119   0.77988628 0.4543650 -0.10715811  1.686314e+00
## 120   0.21944295 0.4389857 -0.61950474  1.080816e+00
## 121  -2.44721248 0.5693577 -3.63686584 -1.409626e+00
## 122  -0.48426902 0.4241624 -1.29546364  3.504740e-01
## 123   0.41176325 0.4291977 -0.39167512  1.263865e+00
## 124   1.44414678 0.4876760  0.54426780  2.435082e+00
## 125   0.78996396 0.4459081 -0.07579134  1.688741e+00
## 126   2.31373451 0.5970732  1.25057231  3.573581e+00
## 127   0.59038236 0.4392470 -0.26815682  1.502259e+00
## 128   0.80416058 0.4469855 -0.06115445  1.668775e+00
## 129   0.98996412 0.4599323  0.10031709  1.922409e+00
## 130  -1.88042348 0.5002812 -2.90731860 -9.500428e-01
## 131  -1.41548072 0.4549095 -2.33274552 -5.391254e-01
## 132  -1.41572128 0.4572916 -2.34044647 -5.530761e-01
## 133  -1.89574753 0.5062231 -2.90986172 -9.646517e-01
## 134  -1.88397966 0.5014153 -2.93385756 -9.536588e-01
## 135   0.79627684 0.4444513 -0.06505130  1.707449e+00
## 136   1.21927207 0.4766909  0.31913074  2.180005e+00
## 137   0.99960916 0.4574650  0.13749655  1.922173e+00
## 138   1.21254171 0.4684017  0.32092221  2.149107e+00
## 139   0.23694231 0.4297022 -0.59710520  1.118978e+00
## 140   0.04965117 0.4198202 -0.76670882  8.681703e-01
## 141   0.41889582 0.4336443 -0.42423433  1.272519e+00
## 142  -0.65556816 0.4354813 -1.52217748  2.080123e-01
## 143   1.44654078 0.4926161  0.53993503  2.453826e+00
## 144   2.30439102 0.5825892  1.25709900  3.521969e+00
## 145  -0.66344110 0.4421332 -1.56208428  1.867154e-01
## 146   0.23209772 0.4295119 -0.59716203  1.074542e+00
## 147  -1.21598728 0.4479828 -2.08255221 -3.608698e-01
## 148   1.97552049 0.5481524  0.97078345  3.089767e+00
## 149   1.69920248 0.5116831  0.76143188  2.752404e+00
## 150   1.21101082 0.4727690  0.31431766  2.159312e+00
## 151   1.45437220 0.5020805  0.50372019  2.506961e+00
## 152   1.98002618 0.5405536  0.99105467  3.087684e+00
## 153  -0.13421399 0.4224687 -0.99052961  6.791692e-01
## 154   0.40919693 0.4312058 -0.43209813  1.253561e+00
## 155  -2.13468385 0.5295769 -3.20403105 -1.155131e+00
## 156   0.04491211 0.4216323 -0.76615969  8.621278e-01
## 157   0.40547847 0.4451712 -0.44993657  1.328026e+00
## 158  -0.84221558 0.4202236 -1.67594163 -2.402756e-02
## 159  -1.89093894 0.4974892 -2.92755277 -9.554584e-01
## 160  -1.63898554 0.4786989 -2.60728520 -7.429357e-01
## 161  -1.43414261 0.4679565 -2.38709286 -5.565354e-01
## 162  -0.48307852 0.4237820 -1.30680223  3.218398e-01
## 163   0.05281477 0.4118885 -0.74235171  8.864644e-01
## 164   0.23281504 0.4289722 -0.59235147  1.095167e+00
## 165   1.21497726 0.4948980  0.27460622  2.217899e+00
## 166   1.20911711 0.4603146  0.31273421  2.138415e+00
## 167   1.20636824 0.4791418  0.30472692  2.157351e+00
## 168  -0.47421851 0.4255053 -1.32005593  3.752478e-01
## 169   0.04965003 0.3996952 -0.71552376  8.206997e-01
## 170   0.05092935 0.4159065 -0.76523338  8.893112e-01
## 171  -2.79091062 0.6225917 -4.09219830 -1.662879e+00
## 172  -1.64811756 0.4895619 -2.62633275 -7.290269e-01
## 173   1.44666194 0.4877549  0.52245588  2.447146e+00
## 174  -1.02336616 0.4464186 -1.90385960 -1.621322e-01
## 175  -0.13124840 0.4074492 -0.92378044  6.659575e-01
## 176  -1.03215484 0.4366852 -1.89679443 -1.794699e-01
## 177   0.22972796 0.4295601 -0.59852147  1.097734e+00
## 178   0.60343273 0.4355983 -0.23417168  1.464717e+00
## 179  -0.48151527 0.4126479 -1.29164856  3.128225e-01
## 180  -2.15088814 0.5210423 -3.20974991 -1.184723e+00
## 181  -1.42480301 0.4660878 -2.36443517 -5.339439e-01
## 182  -0.65494124 0.4259993 -1.49713467  1.838775e-01
## 183   0.04567683 0.4277266 -0.79954679  8.964324e-01
## 184  -1.22560747 0.4417781 -2.13740070 -4.014748e-01
## 185   0.40559544 0.4313084 -0.41313213  1.245528e+00
## 186   1.20966309 0.4747305  0.31161511  2.167485e+00
## 187   0.98757480 0.4589477  0.11015887  1.949027e+00
## 188   0.59961643 0.4351499 -0.22597516  1.465728e+00
## 189   0.41354304 0.4338940 -0.42820258  1.292662e+00
## 190   1.99152064 0.5428609  0.99553108  3.094011e+00
## 191   0.60358536 0.4359873 -0.24325788  1.479164e+00
## 192   1.01253306 0.4512552  0.15812466  1.918374e+00
## 193   1.98180498 0.5392475  0.96706083  3.134837e+00
## 194   1.70166923 0.5260665  0.75399081  2.776540e+00
## 195   0.99969912 0.4560319  0.14118053  1.938356e+00
## 196   1.98159634 0.5551004  0.95713797  3.152206e+00
## 197   1.21342113 0.4638526  0.32450760  2.160605e+00
## 198   1.20936425 0.4799767  0.29305979  2.196948e+00
## 199   1.00433019 0.4674418  0.09208864  1.951799e+00
## 200   2.29307273 0.5965169  1.20850407  3.550738e+00
## 201   1.21690823 0.4703212  0.32602320  2.176173e+00
## 202  -1.87680958 0.5000131 -2.88255569 -9.636341e-01
## 203   0.79331515 0.4453083 -0.07680970  1.679258e+00
## 204   0.22971155 0.4336687 -0.61213242  1.072532e+00
## 205  -0.66032234 0.4222408 -1.48841163  1.603001e-01
## 206  -0.65159700 0.4223467 -1.50473956  1.792566e-01
## 207   0.79743269 0.4507469 -0.06147707  1.734614e+00
## 208   0.99011749 0.4761895  0.10149421  1.968548e+00
## 209  -2.80895806 0.6156175 -4.11697595 -1.696908e+00
## 210  -2.43171938 0.5688012 -3.63594199 -1.399293e+00
## 211  -1.87927777 0.5055585 -2.91309490 -9.324346e-01
## 212  -1.02163278 0.4302055 -1.89883511 -1.934872e-01
## 213   0.78851645 0.4458131 -0.02257435  1.690312e+00
## 214   0.78950467 0.4464727 -0.07715678  1.648694e+00
## 215   1.44417250 0.5072955  0.48615020  2.462557e+00
## 216   0.23972410 0.4159142 -0.59186288  1.058557e+00
## 217   0.41279654 0.4237014 -0.40152315  1.261767e+00
## 218   0.41596053 0.4304202 -0.42799813  1.274041e+00
## 219   1.45761329 0.4889469  0.56577763  2.421260e+00
## 220  -0.12296100 0.4117218 -0.92604258  6.852705e-01
## 221   0.99901283 0.4662850  0.11981607  1.912155e+00
## 222   0.79001592 0.4439947 -0.05735175  1.675403e+00
## 223   0.59488745 0.4408935 -0.25241116  1.499188e+00
## 224   1.00237847 0.4735133  0.11415877  1.922739e+00
## 225   0.99742443 0.4622123  0.09822919  1.921698e+00
## 226   0.23506065 0.4246975 -0.55831657  1.075922e+00
## 227  -1.87973415 0.4764554 -2.88130412 -1.010270e+00
## 228  -1.02545996 0.4346691 -1.89872348 -1.807258e-01
## 229  -1.02281993 0.4270534 -1.86543151 -2.139136e-01
## 230  -3.21520622 0.6823506 -4.63953466 -1.985399e+00
## 231  -0.13001917 0.4160555 -0.95841250  6.904740e-01
## 232  -2.79095142 0.6126969 -4.07802856 -1.685961e+00
## 233  -0.29940693 0.4296626 -1.13891326  5.792376e-01
## 234   1.21491063 0.4819152  0.25899457  2.177249e+00
## 235   1.20688458 0.4765040  0.30432087  2.182313e+00
## 236   1.44402851 0.4908865  0.53797153  2.451256e+00
## 237   1.00315606 0.4496416  0.15490189  1.921337e+00
## 238   0.99508051 0.4594045  0.13399097  1.910503e+00
## 239   0.22651878 0.4237442 -0.58660692  1.078068e+00
## 240  -1.22128845 0.4456972 -2.10224903 -3.793788e-01
## 241   0.04964969 0.4132457 -0.74559627  8.676016e-01
## 242   0.40938934 0.4171712 -0.42339579  1.255754e+00
## 243  -1.21527490 0.4545734 -2.13501417 -3.429522e-01
## 244   1.44793466 0.4932513  0.50193702  2.467458e+00
## 245   1.21277509 0.4779983  0.28243887  2.206692e+00
## 246   1.00002601 0.4559472  0.11835890  1.921709e+00
## 247   1.21940541 0.4868174  0.28897484  2.202195e+00
## 248  -0.66153835 0.4331212 -1.51431558  2.034273e-01
## 249  -0.47715653 0.4183738 -1.28087128  3.238885e-01
## 250  -1.21602230 0.4503202 -2.12788254 -3.337337e-01
## 251   0.04938048 0.4232745 -0.78021717  8.908795e-01
## 252  -1.02410292 0.4405663 -1.92590502 -1.976130e-01
## 253  -0.66016294 0.4336198 -1.51524972  1.854253e-01
## 254  -0.47644489 0.4312406 -1.32776468  3.999063e-01
## 255  -2.14401942 0.5337825 -3.29642851 -1.158063e+00
## 256  -0.65294994 0.4375082 -1.54503391  2.131400e-01
## 257   0.04091047 0.4266098 -0.80212046  8.850115e-01
## 258  -1.21907760 0.4425150 -2.11792825 -3.506216e-01
## 259  -0.64890666 0.4333528 -1.50051806  1.950867e-01
## 260  -1.88638215 0.5020965 -2.91746872 -9.668847e-01
## 261   1.70172817 0.5183718  0.71673887  2.742599e+00
## 262   0.59609515 0.4226970 -0.21850342  1.478018e+00
## 263  -0.30235933 0.4324544 -1.18291359  5.653813e-01
## 264  -0.11557865 0.4205379 -0.94899452  7.009345e-01
## 265  -0.83921977 0.4383111 -1.71869123 -4.141056e-05
## 266  -1.41994704 0.4670555 -2.40371498 -5.263854e-01
## 267   1.21422395 0.4665929  0.34303839  2.130424e+00
## 268  -0.30064231 0.4225216 -1.12599891  5.425853e-01
## 269  -1.21585561 0.4449574 -2.12303468 -3.599112e-01
## 270  -1.65239937 0.4871942 -2.66915099 -7.192729e-01
## 271  -1.87987372 0.4898360 -2.87153319 -9.760592e-01
## 272  -2.14792168 0.5356673 -3.26119856 -1.164957e+00
## 273  -0.65903786 0.4257279 -1.50992481  1.902503e-01
## 274  -0.46789577 0.4265493 -1.29925786  3.678971e-01
## 275  -1.22922285 0.4464701 -2.12414551 -3.764363e-01
## 276  -0.31017936 0.4164411 -1.15196243  5.228128e-01
## 277  -1.02876707 0.4321497 -1.88959158 -2.087827e-01
## 278  -0.48924119 0.4099650 -1.31292992  2.986828e-01
## 279  -1.87744647 0.5071253 -2.91457389 -9.302629e-01
## 280  -1.87287107 0.4996361 -2.85167934 -9.018133e-01
## 281  -2.15111121 0.5542764 -3.31412788 -1.134107e+00
## 282  -1.88614895 0.4953179 -2.91828119 -9.699157e-01
## 283  -2.43365169 0.5664829 -3.61593209 -1.406576e+00
## 284  -2.43903295 0.5810196 -3.66166265 -1.396937e+00
## 285   2.29814041 0.5931950  1.20378093  3.547868e+00
## 286   3.12412350 0.7025081  1.88237020  4.622009e+00
## 287   1.21166651 0.4732099  0.29334619  2.183339e+00
## 288   1.71012348 0.5190354  0.74814713  2.788783e+00
## 289   0.98963237 0.4495043  0.13088587  1.895007e+00
## 290   1.44776412 0.4789321  0.56831012  2.404074e+00
## 291  -1.65062758 0.4634891 -2.55634719 -7.717506e-01
## 292  -0.29427953 0.4320539 -1.15236581  5.496251e-01
## 293  -0.66204560 0.4285785 -1.50071734  1.745852e-01
## 294  -0.83531956 0.4227109 -1.64759912 -1.954799e-02
## 295  -0.84695327 0.4338861 -1.72632764 -4.070271e-03
## 296  -1.22641940 0.4394254 -2.11140925 -3.799975e-01
## 297   0.60009016 0.4300396 -0.22143277  1.453935e+00
## 298   0.99790991 0.4579735  0.11085740  1.907132e+00
## 299  -0.65318365 0.4265964 -1.53622264  1.727922e-01
## 300   0.22517224 0.4397886 -0.65145643  1.111797e+00
## 301   0.59878167 0.4137074 -0.17326774  1.402870e+00
## 302   1.00263278 0.4651231  0.12004266  1.933898e+00
## 303   0.04353344 0.4197818 -0.77411402  8.804655e-01
## 304   0.03787893 0.4323898 -0.78557887  8.891410e-01
## 305   0.59905278 0.4379387 -0.25477022  1.482775e+00
## 306   0.23585791 0.4390839 -0.60847566  1.087143e+00
## 307   0.60010277 0.4246108 -0.20978756  1.451081e+00
## 308   1.00461605 0.4581731  0.13486734  1.922458e+00
## 309  -0.13147802 0.4250582 -0.96520128  7.210170e-01
## 310   0.05316055 0.4230971 -0.75020491  8.997236e-01
## 311   1.96963450 0.5462704  0.94477983  3.104653e+00
## 312   1.98781973 0.5559643  0.95095829  3.151743e+00
## 313   0.79364248 0.4343328 -0.02757179  1.652971e+00
## 314   1.71005880 0.5034951  0.76443670  2.716078e+00
## 315   1.20878304 0.4852562  0.29614596  2.210102e+00
## 316   0.22470734 0.4218006 -0.57678928  1.062937e+00
## 317   1.21617908 0.4696625  0.31174443  2.170646e+00
## 318   0.99962647 0.4675867  0.10890691  1.959867e+00
## 319   1.69981637 0.5121668  0.73173409  2.729901e+00
## 320   0.41085713 0.4347780 -0.41965431  1.284998e+00
## 321  -0.85171085 0.4539365 -1.72830895  2.643289e-02
## 322   0.98538184 0.4517537  0.12761332  1.903531e+00
## 323  -0.30267983 0.4199381 -1.12633257  5.206506e-01
## 324  -1.01875802 0.4320857 -1.88784170 -2.084288e-01
## 325  -1.64162834 0.4658712 -2.58289100 -7.659162e-01
## 326  -0.11922270 0.4140621 -0.93291259  6.945842e-01
## 327  -0.48196904 0.4341537 -1.34035173  3.539696e-01
## 328   0.23420634 0.4325204 -0.59201637  1.087822e+00
## 329  -1.22384962 0.4580227 -2.14823058 -3.363239e-01
## 330  -0.65310207 0.4198357 -1.50126816  1.723760e-01
## 331   0.40825415 0.4404439 -0.45037757  1.294094e+00
## 332   0.40942729 0.4414776 -0.43153706  1.294306e+00
## 333   1.00060036 0.4537587  0.13070552  1.896028e+00
## 334   0.40658671 0.4258157 -0.41953358  1.241480e+00
## 335   1.20677564 0.4698649  0.30710967  2.150547e+00
## 336  -1.02987049 0.4383423 -1.90077002 -2.177029e-01
## 337   0.23625517 0.4080728 -0.55709927  1.043898e+00
## 338  -0.30473002 0.4256226 -1.14263833  5.109185e-01
## 339  -2.14512544 0.5262912 -3.23299124 -1.161198e+00
## 340  -1.63877379 0.4721828 -2.60220510 -7.563616e-01
## 341  -1.22834833 0.4504413 -2.14080654 -3.579262e-01
## 342  -0.85097201 0.4417211 -1.70800629  3.194627e-03
## 343  -0.31145547 0.4188447 -1.14211148  5.153882e-01
## 344  -1.87527466 0.4981406 -2.91031279 -9.369697e-01
## 345   1.43527738 0.4784583  0.51142050  2.401729e+00
## 346   0.59700286 0.4424805 -0.24235797  1.494799e+00
## 347   1.70250555 0.5155415  0.74526770  2.766758e+00
## 348   1.21596718 0.4840774  0.28798216  2.179435e+00
## 349   0.79698592 0.4536559 -0.05691363  1.687131e+00
## 350   1.43876069 0.4832419  0.51629265  2.410937e+00
## 351  -2.43534552 0.5573323 -3.59753739 -1.414226e+00
## 352   1.20737847 0.4708473  0.33041062  2.174296e+00
## 353  -0.65311559 0.4195992 -1.47458985  1.529022e-01
## 354  -0.47954003 0.4262088 -1.35595245  3.554990e-01
## 355  -2.14051446 0.5158174 -3.22331401 -1.172692e+00
## 356  -1.87276640 0.4898428 -2.86484169 -9.267300e-01
## 357  -2.78732154 0.6027512 -4.06233569 -1.697560e+00
## 358  -0.84046756 0.4388096 -1.71347750  1.653315e-02
## 359   1.20942345 0.4867490  0.29327950  2.189220e+00
## 360  -0.83666545 0.4372759 -1.71313718  1.214416e-02
## 361  -1.22816733 0.4528939 -2.15880348 -3.658511e-01
## 362  -1.22427783 0.4463730 -2.11607016 -3.918259e-01
## 363  -2.14464537 0.5378444 -3.24240404 -1.159904e+00
## 364  -1.65194912 0.4825000 -2.63468533 -7.600919e-01
## 365   0.22402432 0.4214150 -0.58360745  1.073205e+00
## 366   1.00237027 0.4641235  0.11549427  1.938006e+00
## 367  -1.21927371 0.4434754 -2.10953228 -3.792235e-01
## 368  -0.48001256 0.4203126 -1.32651123  3.432041e-01
## 369   0.60731636 0.4331679 -0.22116478  1.477754e+00
## 370   0.79531203 0.4386180 -0.04307035  1.665985e+00
## 371   0.23847558 0.4274277 -0.58854510  1.101909e+00
## 372  -0.66525378 0.4326322 -1.54102160  1.662549e-01
## 373  -0.48489662 0.4195675 -1.31479807  3.244346e-01
## 374   1.00506669 0.4675148  0.12607021  1.935660e+00
## 375   0.23403748 0.4245006 -0.56594838  1.078018e+00
## 376   1.21465279 0.4787586  0.30164172  2.185379e+00
## 377   0.79425521 0.4418067 -0.07083854  1.707066e+00
## 378  -0.66569872 0.4270833 -1.50628209  1.586057e-01
## 379   0.78882528 0.4513140 -0.04537081  1.719533e+00
## 380  -1.43087851 0.4686269 -2.35213076 -5.591019e-01
## 381  -1.42827278 0.4619869 -2.35468364 -5.585898e-01
## 382   0.05153796 0.4265570 -0.77555287  8.961596e-01
## 383   1.21511699 0.4715089  0.32791312  2.170659e+00
## 384  -1.21718532 0.4618648 -2.15315397 -3.567567e-01
## 385   1.97411485 0.5320193  0.97060890  3.043084e+00
## 386   0.60235517 0.4315010 -0.23705302  1.463151e+00
## 387  -1.42985951 0.4579654 -2.35805700 -5.785925e-01
## 388   0.60861517 0.4571270 -0.26059503  1.528586e+00
## 389  -0.12255670 0.4272305 -0.96575452  7.087523e-01
## 390  -1.02712256 0.4356811 -1.89390032 -1.705988e-01
## 391  -0.12746330 0.4152430 -0.91939040  7.122102e-01
## 392  -2.44849118 0.5650409 -3.65340461 -1.438190e+00
## 393  -2.12665512 0.5205452 -3.19633979 -1.151683e+00
## 394   0.59046159 0.4368261 -0.24596015  1.456363e+00
## 395   0.05079858 0.4157389 -0.75436043  8.766061e-01
## 396  -1.41883759 0.4556365 -2.30767621 -5.413955e-01
## 397   2.66821810 0.6263833  1.50543074  3.980777e+00
## 398   0.05425051 0.4258482 -0.76728304  8.990670e-01
## 399   1.70405480 0.5148280  0.74564147  2.762803e+00
## 400  -0.83556598 0.4392150 -1.74000022  1.166103e-02
## 401  -0.83155783 0.4359940 -1.69393271  5.383673e-03
## 402  -1.43567531 0.4617395 -2.39620348 -5.507443e-01
## 403   0.22605933 0.4362551 -0.63617496  1.105125e+00
## 404  -1.42924441 0.4640106 -2.35654447 -5.598198e-01
## 405   1.43464022 0.4749559  0.53385729  2.392230e+00
## 406   0.41773968 0.4332486 -0.40077442  1.278310e+00
## 407   1.70851581 0.5137592  0.75280011  2.739352e+00
## 408   1.44399249 0.4832573  0.51801978  2.413917e+00
## 409   0.60207632 0.4506440 -0.26182077  1.485827e+00
## 410   1.70967514 0.5289824  0.71376496  2.805414e+00
## 411  -2.14170811 0.5378771 -3.28118424 -1.148566e+00
## 412  -0.65893151 0.4282475 -1.47889808  1.845068e-01
## 413  -0.31173427 0.4188918 -1.14083600  5.070663e-01
## 414   0.05249723 0.4187592 -0.78693465  9.036545e-01
## 415  -0.13114533 0.4229141 -0.93899628  6.829301e-01
## 416  -1.21481507 0.4443621 -2.12362200 -3.767473e-01
## 417  -0.83152297 0.4254479 -1.68076356 -2.752167e-02
## 418  -2.44587590 0.5667043 -3.59373059 -1.396154e+00
## 419  -0.49056242 0.4246501 -1.32258661  3.492627e-01
## 420  -0.47313750 0.4325819 -1.30677904  3.736472e-01
## 421  -1.42150680 0.4679322 -2.37959750 -5.260128e-01
## 422  -1.21406361 0.4586899 -2.13850497 -3.443269e-01
## 423   0.79755853 0.4619517 -0.07715159  1.752291e+00
## 424  -1.02695129 0.4280210 -1.88285185 -2.033211e-01
## 425  -1.43498074 0.4721933 -2.35942598 -5.412869e-01
## 426   0.22963141 0.4292629 -0.61135177  1.073432e+00
## 427   0.23416905 0.4292075 -0.60420195  1.098094e+00
## 428  -0.31181296 0.4090593 -1.11278826  4.818618e-01
## 429   0.59888433 0.4340339 -0.23169317  1.467144e+00
## 430   0.40673767 0.4166666 -0.40905127  1.224196e+00
## 431  -0.66522665 0.4145938 -1.46510588  1.164036e-01
## 432  -0.47560513 0.4260080 -1.30637941  3.489448e-01
## 433  -0.30476963 0.4198521 -1.12913860  5.060333e-01
## 434   1.43647535 0.4833353  0.50463132  2.456243e+00
## 435  -0.83643810 0.4375277 -1.71287918 -5.594081e-03
## 436   0.23321263 0.4271844 -0.59019720  1.072378e+00
## 437   1.97790265 0.5601998  0.93812988  3.155332e+00
## 438   0.59731142 0.4342180 -0.24471492  1.470572e+00
## 439   1.69795390 0.5133576  0.75110073  2.756929e+00
## 440   0.40703462 0.4309324 -0.41244649  1.251558e+00
## 441   1.44621512 0.5080892  0.50101240  2.443629e+00
## 442   1.97814320 0.5396355  0.98577738  3.117306e+00
## 443   0.77703477 0.4359602 -0.06971615  1.651716e+00
## 444   1.45226313 0.4903877  0.53019286  2.461626e+00
## 445  -1.03716957 0.4298461 -1.87386689 -2.065982e-01
## 446   0.22937686 0.4270967 -0.60187743  1.059345e+00
## 447   0.04797367 0.4264681 -0.79155738  8.806413e-01
## 448  -0.30189109 0.4058096 -1.06751633  4.978983e-01
## 449  -0.13474732 0.4183367 -0.95908243  6.790318e-01
## 450  -0.46525700 0.4111173 -1.25167807  3.358520e-01
## 451   0.40066061 0.4185360 -0.41749886  1.232410e+00
## 452   0.79085755 0.4510487 -0.05590414  1.703119e+00
## 453   0.59793804 0.4341943 -0.22405006  1.474231e+00
## 454  -2.14312328 0.5239239 -3.26532889 -1.181598e+00
## 455  -1.22387786 0.4579635 -2.10834872 -3.328252e-01
## 456   1.21561967 0.4761497  0.33776432  2.178415e+00
## 457   1.21295312 0.4615677  0.33337097  2.157939e+00
## 458   0.22650081 0.4181969 -0.57902920  1.054980e+00
## 459   1.45222996 0.4928938  0.54093845  2.460336e+00
## 460  -0.83909967 0.4256940 -1.67384635 -1.707421e-02
## 461   2.30724564 0.5956801  1.18727356  3.564861e+00
## 462   0.23673922 0.4209761 -0.59212551  1.095522e+00
## 463   1.21043779 0.4611140  0.34795215  2.146198e+00
## 464   0.99919423 0.4551828  0.14054003  1.904174e+00
## 465  -0.84452340 0.4245949 -1.71842660 -7.726168e-03
## 466  -0.48395793 0.4177061 -1.29281705  3.253842e-01
## 467  -0.31026224 0.4304007 -1.15100819  5.311514e-01
## 468   1.69725981 0.5040356  0.75884786  2.733928e+00
## 469   1.00169013 0.4581288  0.13262223  1.945452e+00
## 470   2.30903534 0.5980826  1.19227659  3.534204e+00
## 471   0.99878010 0.4501537  0.13793235  1.912587e+00
## 472   1.98187705 0.5360292  0.99477254  3.101950e+00
## 473   1.21335265 0.4785736  0.31442908  2.169259e+00
## 474   0.40202006 0.4376879 -0.44740337  1.281845e+00
## 475  -0.84069344 0.4324365 -1.67468207  1.607234e-02
## 476  -2.78555322 0.6063672 -4.11411487 -1.695586e+00
## 477  -0.65820915 0.4259970 -1.47065733  1.666968e-01
## 478  -0.84015482 0.4278807 -1.70124688  1.677668e-03
## 479   0.59724969 0.4438364 -0.25284007  1.487236e+00
## 480  -1.88307154 0.5161544 -2.89442639 -9.231172e-01
## 481  -0.66545023 0.4290619 -1.51530582  1.668638e-01
## 482  -1.42135228 0.4567950 -2.33922319 -5.651489e-01
## 483   0.40019274 0.4319151 -0.43489270  1.276846e+00
## 484  -0.12490339 0.4102981 -0.93945423  6.850541e-01
## 485   0.22590632 0.4168699 -0.56371296  1.044334e+00
## 486   0.99192317 0.4392469  0.17638220  1.860567e+00
## 487  -0.65432628 0.4174413 -1.50128457  1.784323e-01
## 488  -0.11975481 0.4213360 -0.92703950  6.936247e-01
## 489   0.04178973 0.4115169 -0.76786305  8.324325e-01
## 490  -1.42883345 0.4557116 -2.37531645 -5.830062e-01
## 491   0.79443094 0.4514030 -0.08577123  1.695770e+00
## 492   0.23536148 0.4243491 -0.59726549  1.094677e+00
## 493  -0.29803779 0.4335880 -1.15831726  5.558245e-01
## 494  -1.22373057 0.4396192 -2.10787362 -3.881208e-01
## 495  -0.84188609 0.4459423 -1.74256408  3.152157e-02
## 496  -0.83503808 0.4222521 -1.66442072 -5.227592e-02
## 497   0.04677545 0.4191415 -0.76818857  8.785092e-01
## 498   1.45921132 0.4903819  0.51749159  2.444198e+00
## 499   0.03983504 0.4271728 -0.77807162  8.886910e-01
## 500   1.45126208 0.4897261  0.52523017  2.435133e+00
## 501  -1.65408777 0.4699956 -2.63312701 -7.788148e-01
## 502  -1.88988482 0.4968446 -2.90777196 -9.560938e-01
## 503  -0.84673136 0.4256387 -1.70039579 -8.088469e-03
## 504  -1.64457881 0.4648795 -2.58493056 -7.570121e-01
## 505  -0.83141656 0.4201890 -1.65622956 -3.268954e-02
## 506  -0.84609634 0.4287656 -1.71898488 -2.762705e-02
## 507   0.40678158 0.4311388 -0.41458644  1.254333e+00
## 508  -1.42372879 0.4505346 -2.31790821 -5.899579e-01
## 509   0.04998579 0.4175819 -0.77033648  8.840401e-01
## 510  -0.65766054 0.4256599 -1.49866752  1.610154e-01
## 511   0.04160916 0.4256438 -0.77041743  9.125779e-01
## 512  -0.65881314 0.4327556 -1.52063745  2.054409e-01
## 513  -0.65863652 0.4247581 -1.51376084  1.662597e-01
## 514  -0.67111576 0.4372098 -1.55836131  1.682207e-01
## 515  -1.21438723 0.4543474 -2.13980218 -3.689771e-01
## 516  -0.46943060 0.4339494 -1.32045355  3.665441e-01
## 517   0.05618990 0.4246997 -0.74934188  9.090358e-01
## 518  -1.65072017 0.4771716 -2.61019929 -7.244553e-01
## 519  -1.41621761 0.4476478 -2.35327632 -5.705246e-01
## 520  -0.83611844 0.4203633 -1.67327608 -5.042915e-02
## 521  -0.84398979 0.4223792 -1.67134945 -1.395874e-02
## 522   0.41038684 0.4432862 -0.46563419  1.301621e+00
## 523  -0.30219687 0.4204114 -1.12595814  5.155214e-01
## 524   1.00084196 0.4649542  0.11799814  1.959260e+00
## 525   0.79486866 0.4458618 -0.04340937  1.719241e+00
## 526   1.70020623 0.5176833  0.72632498  2.749889e+00
## 527  -0.12977664 0.3968165 -0.90885755  6.345676e-01
## 528   0.23590091 0.4259026 -0.58577084  1.096930e+00
## 529  -1.22606097 0.4484151 -2.11608797 -3.774827e-01
## 530  -1.01327719 0.4271955 -1.90772137 -1.811361e-01
## 531   1.21549760 0.4812849  0.31401311  2.183196e+00
## 532  -0.30328227 0.4267308 -1.13286673  5.309852e-01
## 533   0.59744851 0.4343238 -0.23734661  1.483108e+00
## 534  -0.65731132 0.4306723 -1.50240818  1.945320e-01
## 535   0.22719177 0.4300894 -0.60963446  1.075513e+00
## 536   0.78870535 0.4508745 -0.05421006  1.710008e+00
## 537   1.44850898 0.4755575  0.55668529  2.396679e+00
## 538   0.40946147 0.4309846 -0.43599327  1.255741e+00
## 539  -1.64539147 0.4857355 -2.63244488 -7.279685e-01
## 540   2.29242380 0.5688393  1.22899878  3.456764e+00
## 541   0.99759036 0.4632046  0.13164316  1.949463e+00
## 542   0.99788222 0.4637819  0.10082605  1.927228e+00
## 543   1.97834994 0.5548321  0.95006988  3.145671e+00
## 544   0.22937421 0.4294901 -0.61922604  1.100728e+00
## 545   0.79607766 0.4454764 -0.07912754  1.691345e+00
## 546  -0.14124479 0.4204040 -0.97259649  6.988071e-01
## 547  -0.47681104 0.4118961 -1.29017040  3.167746e-01
## 548   1.98027243 0.5510596  0.95880323  3.113135e+00
## 549   0.23386968 0.4170941 -0.57294601  1.061257e+00
## 550   1.46056976 0.5046617  0.53715450  2.488270e+00
## 551   1.00063986 0.4542264  0.14088540  1.918721e+00
## 552   1.68558139 0.5045868  0.74573597  2.714738e+00
## 553  -0.48349427 0.4210583 -1.31432802  3.340491e-01
## 554   1.69249741 0.5115992  0.74231812  2.737150e+00
## 555   1.97521930 0.5419673  0.97316140  3.069546e+00
## 556   0.79069335 0.4370657 -0.03648162  1.685628e+00
## 557   2.68261858 0.6496301  1.48365992  4.055566e+00
## 558  -1.65369140 0.4845811 -2.64437281 -7.603226e-01
## 559  -1.01909283 0.4343598 -1.89667240 -1.888202e-01
## 560  -1.42442731 0.4605272 -2.37911950 -5.436997e-01
## 561  -1.88426279 0.5145225 -2.94218921 -9.233485e-01
## 562  -1.22443834 0.4403676 -2.10247793 -3.748410e-01
## 563  -1.88202412 0.4928813 -2.90750619 -9.588590e-01
## 564   0.05278728 0.4171905 -0.75770882  8.941163e-01
## 565  -0.66352804 0.4244865 -1.49087992  1.686438e-01
## 566  -1.64199769 0.4622782 -2.57284541 -7.857428e-01
## 567  -2.15404674 0.5339507 -3.28621433 -1.188223e+00
## 568  -0.12607388 0.4178936 -0.94050864  6.937810e-01
## 569   1.01001044 0.4468442  0.18474882  1.922090e+00
## 570   0.58768627 0.4426446 -0.27447993  1.444998e+00
## 571  -0.13093675 0.4118854 -0.93769791  6.686107e-01
## 572   0.79928497 0.4539487 -0.07338606  1.705189e+00
## 573   0.23039550 0.4221294 -0.58245351  1.035324e+00
## 574  -0.13935519 0.4160514 -0.96990035  6.721373e-01
## 575   1.97935353 0.5531163  0.93953293  3.146282e+00
## 576   1.99001521 0.5526041  0.95135169  3.113707e+00
## 577   1.20962246 0.4697478  0.32835367  2.144053e+00
## 578   0.42819749 0.4133266 -0.38677797  1.251047e+00
## 579   0.59049918 0.4154698 -0.20593149  1.396128e+00
## 580  -0.30455646 0.4014283 -1.10253039  4.730203e-01
## 581  -0.48203672 0.4107091 -1.28884079  3.092325e-01
## 582  -1.63880730 0.4718644 -2.60831330 -7.660214e-01
## 583  -1.88180634 0.4887302 -2.86777994 -9.652984e-01
## 584   0.59942853 0.4353092 -0.24841790  1.486617e+00
## 585  -1.21598204 0.4483444 -2.13611413 -3.504334e-01
## 586   0.78987339 0.4485243 -0.08347560  1.687983e+00
## 587  -1.41818241 0.4699098 -2.38864221 -5.272462e-01
## 588  -1.42882767 0.4472887 -2.33803416 -5.790391e-01
## 589  -1.02784413 0.4453345 -1.90716099 -1.678911e-01
## 590  -2.14079883 0.5245244 -3.21107434 -1.175033e+00
## 591   0.05451736 0.4185224 -0.79450169  8.728528e-01
## 592  -1.42443194 0.4639340 -2.38573625 -5.264130e-01
## 593   1.97993293 0.5541723  0.96205264  3.131699e+00
## 594   0.59898238 0.4428033 -0.26104942  1.472280e+00
## 595   0.41117050 0.4475539 -0.45237693  1.289188e+00
## 596  -0.46989824 0.4180537 -1.29241535  3.290848e-01
## 597  -0.46746487 0.4161564 -1.26579275  3.333572e-01
## 598  -1.22256759 0.4508705 -2.13131572 -3.630697e-01
## 599  -1.42172339 0.4663471 -2.36196068 -5.377898e-01
## 600   0.78634484 0.4249321 -0.01750172  1.637403e+00
## 601   0.22670155 0.4409489 -0.62257119  1.104620e+00
## 602   1.21550475 0.4788711  0.29776276  2.194169e+00
## 603   0.40069894 0.4220018 -0.42666131  1.228130e+00
## 604   1.70153285 0.5237363  0.71784609  2.781122e+00
## 605   1.69368462 0.5133782  0.74896595  2.766833e+00
## 606   0.04191348 0.4014756 -0.73812755  8.209303e-01
## 607  -0.30873737 0.4358990 -1.16592430  5.447965e-01
## 608   0.77693132 0.4271939 -0.04258147  1.648445e+00
## 609   0.05594914 0.4212466 -0.77205519  9.065375e-01
## 610   1.00251078 0.4550409  0.15034499  1.896628e+00
## 611  -0.83955298 0.4365745 -1.74941341  5.215035e-03
## 612  -0.47480719 0.4163681 -1.29409820  3.261117e-01
## 613   0.40171028 0.4321372 -0.44991767  1.291015e+00
## 614  -1.64425430 0.4876751 -2.63453713 -7.027979e-01
## 615   0.78566418 0.4392264 -0.05114641  1.687685e+00
## 616   1.44508390 0.4860336  0.51952316  2.391784e+00
## 617   0.78850946 0.4499091 -0.08742549  1.668496e+00
## 618  -0.66155944 0.4243360 -1.49856708  1.402340e-01
## 619   1.70755132 0.5312631  0.71167189  2.799457e+00
## 620   0.59317323 0.4363380 -0.23020749  1.472119e+00
## 621  -0.31383408 0.4102097 -1.13037213  4.925810e-01
## 622   1.98056658 0.5550830  0.93896419  3.115180e+00
## 623   1.45198603 0.4716504  0.58604127  2.376580e+00
## 624   0.79930528 0.4506279 -0.06251753  1.696087e+00
## 625   1.45365352 0.4889411  0.52862439  2.468776e+00
## 626   0.22742531 0.4320724 -0.62526380  1.063902e+00
## 627   0.23470953 0.4185156 -0.59410379  1.068582e+00
## 628   0.22447108 0.4203348 -0.55539147  1.080247e+00
## 629  -0.84452367 0.4253135 -1.71356114 -2.317828e-02
## 630  -1.64536593 0.4754285 -2.62190053 -7.480424e-01
## 631   0.99254204 0.4624271  0.11605725  1.927338e+00
## 632  -0.30994315 0.4281448 -1.14766927  5.127100e-01
## 633  -0.29961033 0.4071424 -1.11222214  5.008400e-01
## 634   0.23612904 0.4338989 -0.58333502  1.092241e+00
## 635  -0.47785925 0.4128188 -1.28570944  3.260112e-01
## 636   0.80220085 0.4432596 -0.02664780  1.676215e+00
## 637   2.29483627 0.5922632  1.22259101  3.508239e+00
## 638   0.40597421 0.4421945 -0.44468361  1.289240e+00
## 639   1.44350954 0.4968429  0.51481637  2.475562e+00
## 640   2.31308639 0.5845663  1.23821450  3.500565e+00
## 641   1.70557044 0.5334566  0.69517353  2.795337e+00
## 642  -1.43418250 0.4604355 -2.39419948 -5.888537e-01
## 643  -1.22431915 0.4519752 -2.12276633 -3.674660e-01
## 644  -0.48115413 0.4168498 -1.29899917  3.213114e-01
## 645  -1.02546549 0.4414328 -1.89638663 -1.913024e-01
## 646   0.05272647 0.4208669 -0.78504230  8.925784e-01
## 647   0.41567708 0.4345642 -0.42839733  1.278205e+00
## 648  -1.02999580 0.4294156 -1.89548826 -2.218332e-01
## 649  -1.04022972 0.4413281 -1.90016899 -2.070632e-01
## 650   0.59547517 0.4431895 -0.26118830  1.488368e+00
## 651  -0.84742059 0.4350717 -1.71100214 -2.197968e-02
## 652  -0.47761541 0.4190369 -1.29053975  3.547700e-01
## 653  -1.87051842 0.5039681 -2.87490956 -9.430595e-01
## 654   0.40278924 0.4406332 -0.45034818  1.285776e+00
## 655  -1.43410997 0.4757694 -2.39363604 -5.548392e-01
## 656  -2.42619243 0.5681200 -3.59814572 -1.384220e+00
## 657  -1.41752264 0.4415147 -2.32193550 -5.854171e-01
## 658  -0.83000716 0.4265571 -1.66448285 -1.138144e-02
## 659  -0.65416906 0.4315503 -1.49247235  1.645411e-01
## 660  -1.42537384 0.4617202 -2.38032807 -5.312387e-01
## 661  -2.43796285 0.5510724 -3.56466913 -1.423224e+00
## 662  -1.22268691 0.4433956 -2.08610959 -3.779481e-01
## 663  -2.79751056 0.6297103 -4.11834044 -1.650509e+00
## 664  -1.64895777 0.4736379 -2.61958301 -7.560795e-01
## 665  -1.42031072 0.4601546 -2.33142226 -5.460770e-01
## 666  -2.79103054 0.6202756 -4.08801047 -1.650387e+00
## 667  -1.21926795 0.4444730 -2.08766989 -3.692435e-01
## 668  -1.65236280 0.4808249 -2.60585011 -7.597235e-01
## 669  -1.64823939 0.4737430 -2.62586248 -7.607491e-01
## 670   0.41023169 0.4333120 -0.42419354  1.258720e+00
## 671   0.41587313 0.4326711 -0.43037024  1.282672e+00
## 672  -1.43672665 0.4573850 -2.35724039 -5.657578e-01
## 673  -0.12799255 0.4185836 -0.92670621  6.897313e-01
## 674  -0.84367989 0.4423208 -1.73594788  1.630049e-02
## 675   1.70357581 0.5193880  0.72219646  2.747589e+00
## 676   0.99832304 0.4571354  0.14913278  1.916893e+00
## 677  -0.13440759 0.4144801 -0.92553276  6.864697e-01
## 678   1.00028162 0.4556914  0.12855562  1.939574e+00
## 679   1.69506028 0.5114163  0.71685872  2.762548e+00
## 680  -0.30427991 0.4129164 -1.11308955  4.976905e-01
## 681   1.70690277 0.5112987  0.75977042  2.700093e+00
## 682   0.99166342 0.4446575  0.15897255  1.899525e+00
## 683   0.22703242 0.4249289 -0.59295752  1.058894e+00
## 684   1.69663617 0.5169302  0.73402432  2.742717e+00
## 685   0.41533386 0.4308554 -0.42839032  1.267608e+00
## 686   0.78894314 0.4436019 -0.04930399  1.682230e+00
## 687   0.04738262 0.4167903 -0.76888824  8.706938e-01
## 688   0.39814466 0.4326724 -0.43264413  1.277391e+00
## 689   1.69388297 0.5187335  0.73472786  2.772262e+00
## 690  -0.66177342 0.4245675 -1.48464656  1.694404e-01
## 691  -0.65104272 0.4198614 -1.47814143  1.696666e-01
## 692  -1.21646235 0.4584447 -2.14208101 -3.542065e-01
## 693  -1.02100663 0.4294160 -1.90312452 -1.990392e-01
## 694  -2.14906701 0.5167382 -3.23049106 -1.187242e+00
## 695   0.22256037 0.4177411 -0.57681686  1.062833e+00
## 696  -0.30160880 0.4101027 -1.11089971  5.230884e-01
## 697  -1.89572512 0.5174306 -2.95775815 -9.334408e-01
## 698  -1.63212241 0.4850243 -2.63916192 -7.375512e-01
## 699  -0.30133326 0.4268155 -1.14275667  5.227014e-01
## 700  -0.83231703 0.4319085 -1.68454703 -7.926992e-04
## 701  -0.48602590 0.4319125 -1.34208670  3.635876e-01
## 702  -1.21996397 0.4473104 -2.12837509 -3.489894e-01
## 703  -0.11977821 0.4117156 -0.92464370  6.773832e-01
## 704   0.22716400 0.4169322 -0.57811690  1.030993e+00
## 705  -0.84217591 0.4376185 -1.72230396  5.724304e-03
## 706   1.70210301 0.5065064  0.76847547  2.688939e+00
## 707   1.97926587 0.5425506  0.96543388  3.129102e+00
## 708   1.00360139 0.4746650  0.08737742  1.984295e+00
## 709  -0.29756877 0.4189342 -1.12708642  4.965545e-01
## 710   0.99853753 0.4715038  0.10392952  1.934726e+00
## 711  -0.48330028 0.4228776 -1.32522228  3.530885e-01
## 712  -1.21693294 0.4500944 -2.13156197 -3.525213e-01
## 713  -1.42621468 0.4674263 -2.38537970 -5.460426e-01
## 714  -0.30046874 0.4309729 -1.15301232  5.469182e-01
## 715  -1.22526606 0.4418052 -2.13306043 -3.937088e-01
## 716  -1.64456728 0.4793213 -2.61315429 -7.779251e-01
## 717   0.79508921 0.4591884 -0.09170438  1.714994e+00
## 718  -0.65856482 0.4268995 -1.52469769  1.705390e-01
## 719   0.78929013 0.4339277 -0.04059491  1.649381e+00
## 720   1.20430308 0.4761883  0.28639179  2.141590e+00
## 721   1.23097943 0.4750806  0.32995586  2.189105e+00
## 722  -2.14369152 0.5277669 -3.21996480 -1.186927e+00
## 723  -0.12532450 0.4215354 -0.93004375  6.765377e-01
## 724   0.22980898 0.4149090 -0.55804439  1.050581e+00
## 725  -1.42386017 0.4512459 -2.33114527 -5.773535e-01
## 726  -0.29665578 0.4160413 -1.10252313  5.437491e-01
## 727  -1.42025966 0.4547975 -2.32889006 -5.692137e-01
## 728  -1.88498630 0.5067292 -2.94183906 -9.333013e-01
## 729   0.41382934 0.4191082 -0.40339292  1.245463e+00
## 730  -1.64175555 0.4794963 -2.62598328 -7.615392e-01
## 731  -1.02856684 0.4325150 -1.89700060 -1.957465e-01
## 732  -0.47408611 0.4253076 -1.29966021  3.479041e-01
## 733   0.23289176 0.4278503 -0.57334717  1.096484e+00
## 734   0.59637487 0.4337040 -0.23868841  1.458744e+00
## 735   0.04434542 0.4138621 -0.75356931  8.476241e-01
## 736  -1.21463032 0.4471991 -2.12435982 -3.711090e-01
## 737  -0.12453421 0.4372346 -0.98257181  7.350390e-01
## 738   1.45471460 0.4898718  0.52914074  2.463472e+00
## 739  -0.12595920 0.4274063 -0.96467246  7.353275e-01
## 740  -1.63951533 0.4775829 -2.62309919 -7.404115e-01
## 741  -0.30773163 0.4277965 -1.15937360  5.205351e-01
## 742   0.59320260 0.4412812 -0.24325969  1.438820e+00
## 743   2.30887983 0.5953781  1.21590424  3.605234e+00
## 744   1.21400228 0.4730857  0.29372029  2.165482e+00
## 745  -0.48241135 0.4248334 -1.31645594  3.595385e-01
## 746   0.23256932 0.4262814 -0.59332347  1.072587e+00
## 747   0.21996679 0.4174967 -0.59228816  1.037430e+00
## 748   0.05647747 0.4128054 -0.76014854  8.715323e-01
## 749   0.05255442 0.4238282 -0.74190210  8.868253e-01
## 750  -0.12503265 0.4222526 -0.94286541  6.984740e-01
## 751  -1.22817259 0.4600381 -2.14368025 -3.289105e-01
## 752   0.04242783 0.4330182 -0.82059275  8.966472e-01
## 753  -1.22466343 0.4367866 -2.11089013 -3.916046e-01
## 754   1.22325836 0.4730824  0.32455826  2.200544e+00
## 755  -0.48560216 0.4141034 -1.30093690  3.170542e-01
## 756  -0.11499560 0.4258673 -0.95256310  7.172231e-01
## 757  -0.30393975 0.4225615 -1.11445641  5.333921e-01
## 758   0.40271894 0.4299024 -0.41995647  1.257974e+00
## 759   0.59450263 0.4421957 -0.24589048  1.484480e+00
## 760   0.78872499 0.4651506 -0.09305385  1.709396e+00
## 761   0.77772022 0.4421954 -0.06282712  1.664163e+00
## 762   0.99827746 0.4616915  0.12912610  1.946857e+00
## 763   1.00111288 0.4635897  0.14254488  1.956493e+00
## 764  -0.29820142 0.4226849 -1.16355120  5.164864e-01
## 765   1.71188722 0.5324600  0.76088231  2.824610e+00
## 766   0.99394042 0.4564510  0.13760291  1.954693e+00
## 767   1.98323401 0.5482795  0.95588774  3.127796e+00
## 768   1.01160012 0.4626162  0.12279762  1.954806e+00
## 769   1.69898376 0.5178507  0.73523577  2.779125e+00
## 770   1.69415134 0.5297033  0.69591503  2.806621e+00
## 771   1.44703226 0.4919475  0.53776346  2.471133e+00
## 772   0.79888853 0.4457059 -0.06409449  1.671145e+00
## 773   1.96820362 0.5334491  0.97383683  3.087708e+00
## 774   1.96835275 0.5569374  0.90955036  3.121307e+00
## 775   0.60353940 0.4398783 -0.26585526  1.482528e+00
## 776   2.28422729 0.5954264  1.20337660  3.518713e+00
## 777   1.69965906 0.5198739  0.70835101  2.738292e+00
## 778   1.71061395 0.5182839  0.74588153  2.771408e+00
## 779   0.60091947 0.4426841 -0.26191623  1.471934e+00
## 780   0.41396618 0.4359687 -0.41866380  1.309104e+00
## 781   3.14370230 0.7310532  1.84221970  4.676724e+00
## 782   0.23257974 0.4379317 -0.60236013  1.093418e+00
## 783   0.99147287 0.4618284  0.10947331  1.909710e+00
## 784   1.69619702 0.5011000  0.75323633  2.748408e+00
## 785   0.59845567 0.4398451 -0.22467425  1.481673e+00
## 786   2.30881792 0.6044773  1.22338327  3.526953e+00
## 787   0.59397240 0.4544932 -0.28801729  1.490256e+00
## 788  -0.66499728 0.4409589 -1.52458570  2.058062e-01
## 789  -0.48793515 0.4232326 -1.31675484  3.406615e-01
## 790  -0.85103899 0.4252308 -1.68339109 -3.480961e-02
## 791  -0.30524724 0.4197471 -1.12414644  5.133568e-01
## 792   0.41052409 0.4223051 -0.39575513  1.260587e+00
## 793   0.41410330 0.4423871 -0.44783758  1.287819e+00
## 794   0.04995319 0.4252584 -0.77095772  8.820595e-01
## 795  -1.87495162 0.4824594 -2.88217907 -9.272404e-01
## 796  -1.42344479 0.4745458 -2.39237379 -5.475636e-01
## 797  -1.42693331 0.4608529 -2.34218733 -5.595504e-01
## 798  -0.83283137 0.4226613 -1.69301502 -1.725150e-02
## 799   1.44383385 0.4891654  0.51285339  2.455144e+00
## 800  -0.84664011 0.4297948 -1.71863556 -1.416219e-02
## 801  -1.64607335 0.4685655 -2.60417141 -7.681328e-01
## 802  -3.22002867 0.6967839 -4.70792459 -1.958689e+00
## 803  -1.02057485 0.4318923 -1.88705047 -2.199853e-01
## 804  -1.43264193 0.4759969 -2.38721484 -5.615225e-01
## 805  -1.02096777 0.4371918 -1.89468639 -1.743639e-01
## 806  -0.48034624 0.4249714 -1.30568380  3.590071e-01
## 807   0.05137448 0.4196841 -0.76987272  8.749415e-01
## 808   0.59422614 0.4524922 -0.26327991  1.493348e+00
## 809  -2.14531571 0.5304067 -3.24631247 -1.155208e+00
## 810  -0.13049364 0.4147541 -0.91867817  6.879644e-01
## 811  -1.87912837 0.5044413 -2.88410747 -9.662015e-01
## 812  -0.84398901 0.4324937 -1.71215431 -2.615325e-02
## 813  -1.43114053 0.4664262 -2.35807311 -5.255731e-01
## 814  -0.83239237 0.4295209 -1.69576200  9.545832e-03
## 815  -2.13517342 0.5262513 -3.24686991 -1.171303e+00
## 816   0.40757115 0.4258122 -0.41742136  1.268224e+00
## 817   0.05156391 0.4322826 -0.78275299  9.023105e-01
## 818  -1.21613083 0.4458441 -2.14109677 -3.648019e-01
## 819  -3.23195041 0.7234675 -4.79356054 -1.947549e+00
## 820  -1.87179638 0.4918165 -2.85833006 -9.570871e-01
## 821  -2.80020520 0.6385424 -4.15610439 -1.663304e+00
## 822  -2.77742364 0.5943258 -4.05695083 -1.682719e+00
## 823  -1.89071896 0.4922255 -2.88937314 -9.520374e-01
## 824  -1.87719665 0.5060260 -2.90782737 -9.247771e-01
## 825  -1.87026477 0.5082180 -2.91340158 -9.216632e-01
## 826  -0.30913465 0.4269490 -1.12279961  5.153518e-01
## 827  -2.79094097 0.5941861 -4.06123819 -1.717323e+00
## 828  -1.22822225 0.4511725 -2.13501225 -3.741163e-01
## 829  -1.02123720 0.4305773 -1.87070966 -1.865764e-01
## 830  -1.22621419 0.4548892 -2.15089517 -3.749338e-01
## 831  -1.02681603 0.4374550 -1.94130808 -2.373038e-01
## 832  -1.44113421 0.4719718 -2.40158313 -5.299352e-01
## 833   0.79459165 0.4457427 -0.09435037  1.697770e+00
## 834   1.69857894 0.5103598  0.72482369  2.766139e+00
## 835   0.05118938 0.4059426 -0.73477863  8.358316e-01
## 836   0.40746651 0.4285235 -0.44326189  1.269447e+00
## 837  -1.01977248 0.4405153 -1.89291810 -1.525919e-01
## 838   1.44229159 0.4878802  0.54065006  2.430528e+00
## 839   0.22394649 0.4113753 -0.56043630  1.050349e+00
## 840   1.69282747 0.5265905  0.74066719  2.789780e+00
## 841   0.99328950 0.4474348  0.14048480  1.896463e+00
## 842   0.58312172 0.4221102 -0.22916931  1.438402e+00
## 843   0.22698583 0.4168843 -0.58752805  1.073970e+00
## 844  -0.48046027 0.4104745 -1.28870808  3.140589e-01
## 845   1.00734684 0.4787749  0.08250753  1.980898e+00
## 846   0.22112777 0.4109379 -0.57142538  1.006650e+00
## 847  -1.20908333 0.4297136 -2.05409574 -4.011359e-01
## 848   1.70062406 0.5196483  0.71493149  2.750889e+00
## 849  -3.22527792 0.7022941 -4.73571688 -1.976449e+00
## 850   0.40979394 0.4288141 -0.43204996  1.258633e+00
## 851  -0.29882849 0.4174198 -1.08089948  5.386492e-01
## 852   0.06130880 0.4388103 -0.77149488  9.208190e-01
## 853  -1.02434301 0.4372377 -1.89437180 -1.677692e-01
## 854  -0.12713726 0.4110258 -0.90383981  6.726942e-01
## 855  -1.43386606 0.4655494 -2.37668755 -5.431325e-01
## 856  -1.21375860 0.4556898 -2.13786292 -3.478444e-01
## 857  -2.78661811 0.6123781 -4.10248864 -1.696089e+00
## 858  -1.02174386 0.4434576 -1.93214397 -1.678692e-01
## 859  -0.47288039 0.4217475 -1.28315808  3.585715e-01
## 860  -0.47691630 0.4313894 -1.32837317  3.761593e-01
## 861  -1.64172717 0.4785678 -2.61745821 -7.464399e-01
## 862  -1.02530684 0.4337357 -1.87105356 -1.898322e-01
## 863   0.23387370 0.4314214 -0.60393629  1.097754e+00
## 864  -1.02617194 0.4380154 -1.89167315 -1.830695e-01
## 865   0.58697991 0.4433650 -0.26436020  1.485338e+00
## 866   0.05822742 0.4268022 -0.77090581  8.935302e-01
## 867   0.78205883 0.4459674 -0.07408247  1.693928e+00
## 868   1.22088183 0.4809190  0.31305488  2.217160e+00
## 869  -0.63997308 0.4393719 -1.50683553  2.467653e-01
## 870  -0.12299989 0.4087695 -0.91350451  6.680873e-01
## 871  -0.29920066 0.4051027 -1.09070886  5.071973e-01
## 872   0.23012673 0.4300899 -0.58930560  1.090269e+00
## 873  -1.63572725 0.4822011 -2.63451157 -7.076269e-01
## 874  -2.13504002 0.5277636 -3.23647254 -1.160966e+00
## 875  -1.87925172 0.4909877 -2.84749883 -9.642433e-01
## 876   0.40446851 0.4305002 -0.43845963  1.275879e+00
## 877  -1.20611669 0.4363590 -2.09723860 -3.646782e-01
## 878  -1.01927180 0.4455500 -1.91728783 -1.724017e-01
## 879  -0.84033218 0.4199970 -1.67226063 -1.997837e-02
## 880   0.05350069 0.4343738 -0.77833364  9.073431e-01
## 881  -1.42743874 0.4545418 -2.35226230 -5.420684e-01
## 882  -1.87659471 0.5128454 -2.93219499 -9.191748e-01
## 883   0.40882160 0.4238629 -0.39795184  1.237974e+00
## 884   0.58660330 0.4296777 -0.23940168  1.459036e+00
## 885  -0.66495053 0.4381994 -1.52582530  2.104510e-01
## 886  -1.64870825 0.4920805 -2.64388424 -7.252999e-01
## 887   1.21706544 0.4757811  0.33107311  2.196025e+00
## 888  -0.47950692 0.4384128 -1.39387262  3.633398e-01
## 889  -0.13155665 0.4316751 -0.97178951  7.111907e-01
## 890  -0.48507190 0.4208992 -1.31719547  3.561830e-01
## 891  -1.22498370 0.4575929 -2.11429890 -3.593018e-01
## 892  -0.48483911 0.4412932 -1.38575325  3.772862e-01
## 893  -0.64495423 0.4201107 -1.48098981  1.748773e-01
## 894  -0.30618510 0.4228462 -1.13436961  5.127733e-01
## 895   0.79187908 0.4528580 -0.06686921  1.693437e+00
## 896   0.40621031 0.4357628 -0.43701654  1.253582e+00
## 897  -2.14924222 0.5383010 -3.25822849 -1.150523e+00
## 898  -1.42675435 0.4567170 -2.36550380 -5.720945e-01
## 899  -0.65474027 0.4106756 -1.46918060  1.303954e-01
## 900   1.97736631 0.5535751  0.94848823  3.071672e+00
## 901  -1.22423343 0.4403594 -2.12762695 -3.900730e-01
## 902   0.41341695 0.4306562 -0.41172761  1.257481e+00
## 903  -1.03035575 0.4489965 -1.92305775 -1.372675e-01
## 904  -0.83689782 0.4201371 -1.68253065 -1.164341e-02
## 905  -1.42253348 0.4492491 -2.33957606 -5.774981e-01
## 906   0.60692221 0.4413440 -0.23534825  1.484210e+00
## 907   1.20601448 0.4570801  0.35819779  2.146547e+00
## 908   1.71103053 0.5223023  0.73975455  2.763342e+00
## 909   1.98358090 0.5425064  0.98020181  3.066144e+00
## 910   0.78989693 0.4495626 -0.06203640  1.644969e+00
## 911   1.21122784 0.4752654  0.31896186  2.166381e+00
## 912   0.05027282 0.4193054 -0.76700901  8.544628e-01
## 913  -1.64102284 0.4802894 -2.62917168 -7.384456e-01
## 914  -1.22808837 0.4461772 -2.11490994 -3.919656e-01
## 915  -1.43868595 0.4571905 -2.36657520 -5.641768e-01
## 916  -0.48134680 0.4299126 -1.33300944  3.822074e-01
## 917   0.05065820 0.4161170 -0.76158668  8.670457e-01
## 918   1.43699813 0.5026312  0.51244394  2.475378e+00
## 919   0.78043618 0.4435975 -0.06911461  1.684072e+00
## 920  -0.12807195 0.4212337 -0.93406513  7.092060e-01
## 921   1.46038688 0.5188192  0.49006277  2.567453e+00
## 922  -0.65118244 0.4314821 -1.51583006  2.134476e-01
## 923  -0.83227178 0.4308425 -1.66939400  1.836852e-02
## 924   0.05567286 0.4317017 -0.79211841  9.232811e-01
## 925  -2.13201745 0.5275270 -3.20942516 -1.143238e+00
## 926   0.99134600 0.4572970  0.11028696  1.898332e+00
## 927   0.59412874 0.4415976 -0.24894774  1.460347e+00
## 928   0.79400334 0.4476520 -0.05415934  1.701425e+00
## 929   0.79839955 0.4532159 -0.08093120  1.696368e+00
## 930   0.23147864 0.4137614 -0.55879472  1.065216e+00
## 931  -1.42615715 0.4679567 -2.36989514 -5.496176e-01
## 932   0.41201646 0.4328467 -0.42347697  1.243708e+00
## 933  -1.64966537 0.4966358 -2.64753440 -6.962280e-01
## 934  -0.30078775 0.4410450 -1.15236633  5.604554e-01
## 935  -1.88749590 0.4932334 -2.88768162 -9.688579e-01
## 936  -1.88234943 0.4920212 -2.88352390 -9.572380e-01
## 937  -1.02088521 0.4363210 -1.89603329 -1.718425e-01
## 938  -0.84486564 0.4232872 -1.70972858 -6.571348e-02
## 939  -1.42507000 0.4539823 -2.33059671 -5.732010e-01
## 940  -0.83060591 0.4380072 -1.69216613  1.408398e-02
## 941  -0.30801358 0.4294108 -1.14707486  5.363116e-01
## 942   0.05163672 0.4100202 -0.73072556  8.603765e-01
## 943  -0.30388664 0.4182628 -1.13029079  5.303154e-01
## 944   0.40580141 0.4456497 -0.44284340  1.287220e+00
## 945   0.04225958 0.4199566 -0.76998847  8.561453e-01
## 946   0.22609219 0.4318985 -0.61913772  1.090303e+00
## 947  -3.20686738 0.7105497 -4.70579177 -1.918319e+00
## 948   0.78610127 0.4633218 -0.12155038  1.716389e+00
## 949   1.20848691 0.4880388  0.24957518  2.222786e+00
## 950   1.21490456 0.4722795  0.32562246  2.148827e+00
## 951   1.00553702 0.4609970  0.14070689  1.943650e+00
## 952  -0.66619377 0.4204516 -1.49293652  1.441662e-01
## 953  -0.13005018 0.4274838 -0.97978235  7.034851e-01
## 954   0.99647173 0.4497564  0.13984190  1.886529e+00
## 955   0.23222459 0.4312563 -0.60049276  1.097144e+00
## 956  -2.16247275 0.5495156 -3.30519682 -1.147517e+00
## 957  -2.45097623 0.5641846 -3.59834333 -1.444458e+00
## 958  -1.02251534 0.4396289 -1.89333772 -1.817399e-01
## 959  -1.43564389 0.4618083 -2.40369159 -5.731161e-01
## 960  -0.47961203 0.4217910 -1.30067203  3.437551e-01
## 961  -1.42143712 0.4569849 -2.35225068 -5.447469e-01
## 962  -0.85076516 0.4404195 -1.73435738 -1.329945e-02
## 963   0.23246925 0.4376796 -0.63028793  1.100607e+00
## 964   1.97895506 0.5514318  0.95757673  3.124831e+00
## 965   1.00564113 0.4551914  0.14677973  1.912042e+00
## 966   0.99920752 0.4648443  0.12131264  1.903210e+00
## 967   0.98624085 0.4536941  0.10260681  1.907072e+00
## 968   0.04849497 0.4188586 -0.76179405  8.717779e-01
## 969   0.99610449 0.4533720  0.14102825  1.919086e+00
## 970   1.00139012 0.4630331  0.11766646  1.923547e+00
## 971  -0.84139402 0.4361004 -1.72502387 -1.978589e-02
## 972  -0.30315359 0.4151909 -1.10199243  5.224065e-01
## 973   0.41104192 0.4322761 -0.41586859  1.259390e+00
## 974   1.21846511 0.4745328  0.30630744  2.168915e+00
## 975  -1.42026024 0.4588309 -2.35128841 -5.491277e-01
## 976   0.40657055 0.4390366 -0.44853386  1.282077e+00
## 977   0.05290146 0.4269867 -0.74600529  9.000768e-01
## 978  -0.65450068 0.4251751 -1.51569521  1.792372e-01
## 979  -0.30923932 0.4235316 -1.14957417  5.358137e-01
## 980  -0.12585952 0.4170527 -0.94148460  6.982148e-01
## 981   1.21027744 0.4650433  0.30218998  2.162969e+00
## 982   0.41288175 0.4519592 -0.46362053  1.320963e+00
## 983  -0.28978400 0.4080427 -1.07048039  5.080007e-01
## 984  -0.49018399 0.4333481 -1.34248244  3.634741e-01
## 985  -0.66220352 0.4244079 -1.48668491  1.484484e-01
## 986  -0.29523347 0.4271922 -1.11892631  5.508178e-01
## 987  -1.64378756 0.4890997 -2.63574451 -7.268991e-01
## 988  -1.22159127 0.4563014 -2.13200848 -3.598227e-01
## 989  -1.02571205 0.4388117 -1.90489018 -1.801677e-01
## 990   1.97914899 0.5364087  0.98603925  3.091331e+00
## 991   0.60134158 0.4434710 -0.27355651  1.484138e+00
## 992  -0.48895415 0.4150532 -1.31498014  3.286416e-01
## 993   0.04425267 0.4313596 -0.78073039  8.989311e-01
## 994   1.00304343 0.4558372  0.14399519  1.925770e+00
## 995  -1.65164327 0.4858428 -2.66162484 -7.291912e-01
## 996  -1.64972385 0.4897483 -2.65807934 -7.284504e-01
## 997  -0.83428035 0.4377027 -1.72085336 -1.386650e-02
## 998   0.40769277 0.4370891 -0.42986216  1.273147e+00
## 999   0.59227261 0.4398192 -0.25721886  1.447935e+00
## 1000  0.04351597 0.4266012 -0.80548979  8.894334e-01
## 1001 -0.13017712 0.4334486 -0.97803418  7.334917e-01
## 1002  1.45058335 0.4917103  0.52775919  2.445863e+00
## 1003  1.21294131 0.4705315  0.32191946  2.154118e+00
## 1004  0.78853659 0.4571980 -0.10952354  1.711710e+00
## 1005 -1.88388870 0.5052946 -2.93220590 -9.609528e-01
## 1006 -2.13542931 0.5205871 -3.21861084 -1.158773e+00
## 1007 -0.30522382 0.4389936 -1.15611971  5.575267e-01
## 1008 -2.15089970 0.5338278 -3.22153634 -1.175643e+00
## 1009 -2.45892853 0.5800554 -3.67821975 -1.428937e+00
## 1010 -1.87558948 0.5069358 -2.94960294 -9.317278e-01
## 1011  1.44766525 0.4959894  0.51993244  2.456687e+00
## 1012 -0.65516057 0.4283956 -1.49708801  1.828319e-01
## 1013 -0.29362328 0.4224685 -1.10326976  5.554761e-01
## 1014 -0.13102825 0.4170178 -0.97066073  6.725169e-01
## 1015 -0.83266367 0.4279445 -1.65683737 -1.334469e-02
## 1016 -0.84629814 0.4326577 -1.69718378 -3.318095e-02
## 1017  0.79434068 0.4446659 -0.05548205  1.666344e+00
## 1018  0.05170848 0.4358085 -0.78436592  9.075003e-01
## 1019 -0.48469624 0.4135659 -1.31112340  2.991684e-01
## 1020 -1.02000003 0.4361044 -1.89650070 -1.829372e-01
## 1021  1.00022744 0.4602700  0.11088821  1.931885e+00
## 1022 -0.13175618 0.4365659 -1.00187778  7.301598e-01
## 1023  0.41676559 0.4187769 -0.40659788  1.236953e+00
## 1024  0.04706047 0.4322626 -0.82098517  9.109948e-01
## 1025  0.59307625 0.4303624 -0.23718983  1.439292e+00
## 1026  0.77883288 0.4455927 -0.07963697  1.664599e+00
## 1027  0.60585309 0.4324711 -0.21923407  1.472469e+00
## 1028  1.70623271 0.5205581  0.74961448  2.778079e+00
## 1029  1.21834462 0.4738495  0.32306421  2.194164e+00
## 1030  0.79480063 0.4514684 -0.06183413  1.694776e+00
## 1031  0.22283842 0.4345059 -0.61330796  1.090416e+00
## 1032  0.99067096 0.4532333  0.13361833  1.907405e+00
## 1033  0.60259544 0.4379739 -0.24395238  1.465057e+00
## 1034  1.20313553 0.4626437  0.32942595  2.192653e+00
## 1035  1.68854440 0.5168788  0.71598515  2.770415e+00
## 1036 -0.83967760 0.4139782 -1.67511351 -5.425284e-02
## 1037 -0.11414118 0.4290324 -0.98344991  7.252289e-01
## 1038  0.41393859 0.4218960 -0.39934978  1.264303e+00
## 1039 -0.66047158 0.4245400 -1.48447314  1.591288e-01
## 1040 -0.64930521 0.4169523 -1.47753083  1.646996e-01
## 1041  1.20298728 0.4662947  0.31698408  2.129846e+00
## 1042  1.97978985 0.5410642  0.97470605  3.102250e+00
## 1043  0.99209699 0.4554358  0.11152723  1.904439e+00
## 1044  1.71050393 0.5300166  0.71855475  2.793036e+00
## 1045  1.98097233 0.5338344  0.99777314  3.095965e+00
## 1046  0.41526117 0.4292421 -0.39777280  1.291174e+00
## 1047  1.45424008 0.4990472  0.52815738  2.487980e+00
## 1048  0.04604476 0.4217521 -0.78452067  9.090589e-01
## 1049  1.45352098 0.4971734  0.53455066  2.440044e+00
## 1050  3.10453996 0.6975961  1.84176439  4.572022e+00
## 1051  2.67287575 0.6346516  1.53422888  3.970778e+00
## 1052  1.97630654 0.5592587  0.96827555  3.134931e+00
## 1053  1.98043374 0.5572150  0.93111171  3.134036e+00
## 1054  1.44839708 0.4934104  0.50547031  2.457419e+00
## 1055  0.04915386 0.4227713 -0.79169027  8.971742e-01
## 1056  0.22226701 0.4203083 -0.59931327  1.073592e+00
## 1057  0.59692109 0.4412397 -0.22529218  1.464302e+00
## 1058  1.21208857 0.4826808  0.31244573  2.170827e+00
## 1059  1.70596567 0.5131116  0.75089375  2.756368e+00
## 1060 -0.13129112 0.4153994 -0.95060768  6.815438e-01
## 1061  0.78826901 0.4442776 -0.07585408  1.690682e+00
## 1062 -1.89284870 0.5009138 -2.91139338 -9.712107e-01
## 1063 -2.43153486 0.5794878 -3.60110638 -1.361582e+00
## 1064 -3.22054850 0.7000607 -4.71482956 -1.998683e+00
## 1065  0.59987674 0.4413647 -0.25225785  1.499710e+00
## 1066  2.30521719 0.5925177  1.19782139  3.536442e+00
## 1067  0.22333883 0.4182218 -0.58419757  1.069695e+00
## 1068  1.71010345 0.5199039  0.74737972  2.786508e+00
## 1069 -0.85296166 0.4275054 -1.70173232 -2.442826e-02
## 1070 -0.48803070 0.4127872 -1.29379181  3.314370e-01
## 1071  0.41442663 0.4287218 -0.42911814  1.272433e+00
## 1072  2.29959899 0.5878392  1.20136215  3.541600e+00
## 1073  1.20696978 0.4702705  0.28001572  2.156712e+00
## 1074  1.21913447 0.4910883  0.28161729  2.235583e+00
## 1075  0.99838847 0.4549759  0.11099236  1.943196e+00
## 1076  1.70481216 0.5101353  0.75749989  2.780738e+00
## 1077  1.22290663 0.4799747  0.30623566  2.193178e+00
## 1078 -0.30338231 0.4232869 -1.15738686  5.362177e-01
## 1079  1.44534464 0.5046884  0.51131045  2.465625e+00
## 1080  1.21080397 0.4769314  0.33992073  2.135494e+00
## 1081  0.58902410 0.4412558 -0.25456977  1.460254e+00
## 1082  0.99921656 0.4757785  0.09555629  1.972798e+00
## 1083  0.42186786 0.4369449 -0.42110793  1.286200e+00
## 1084 -0.82663621 0.4281414 -1.67470213 -2.872992e-03
## 1085 -0.83716285 0.4280256 -1.69959358 -2.068806e-02
## 1086 -0.65870730 0.4203587 -1.49339494  1.484657e-01
## 1087 -0.12203133 0.4391319 -0.95305400  7.509778e-01
## 1088 -1.63227882 0.4733726 -2.65168132 -7.244617e-01
## 1089  1.45288336 0.4889553  0.54521738  2.463032e+00
## 1090  0.98943048 0.4645522  0.09981998  1.920633e+00
## 1091  1.20865261 0.4717886  0.32671221  2.178657e+00
## 1092  0.22562158 0.4277574 -0.59651846  1.096077e+00
## 1093  1.45380121 0.4893025  0.53262833  2.448931e+00
## 1094  0.79260424 0.4416945 -0.05712052  1.694844e+00
## 1095 -0.12307994 0.4226737 -0.96442383  7.073865e-01
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(modelo\_2pl)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Family: bernoulli 
##   Links: mu = logit 
## Formula: response ~ 1 + (1 | id) + (1 | item) 
##    Data: data_long (Number of observations: 28470) 
##   Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
##          total post-warmup draws = 4000
## 
## Multilevel Hyperparameters:
## ~id (Number of levels: 1095) 
##               Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## sd(Intercept)     1.29      0.04     1.23     1.37 1.00      952     1965
## 
## ~item (Number of levels: 26) 
##               Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## sd(Intercept)     1.16      0.18     0.89     1.58 1.00      721     1149
## 
## Regression Coefficients:
##           Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
## Intercept     0.11      0.22    -0.32     0.57 1.01      240      709
## 
## Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
## and Tail_ESS are effective sample size measures, and Rhat is the potential
## scale reduction factor on split chains (at convergence, Rhat = 1).
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#ver dificultad de cada ítem}
\FunctionTok{ranef}\NormalTok{(modelo\_2pl)}\SpecialCharTok{$}\NormalTok{item}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## , , Intercept
## 
##             Estimate Est.Error        Q2.5       Q97.5
## R040Q02   0.46231191 0.2325999 -0.00883768  0.92036008
## R040Q03A -0.04460510 0.2323458 -0.50999091  0.40944269
## R040Q03B -1.11205821 0.2319697 -1.57580820 -0.66278501
## R040Q04   1.27757467 0.2369253  0.79705955  1.73653395
## R040Q06   0.16708789 0.2314248 -0.30242436  0.62613427
## R077Q02   1.19513944 0.2342135  0.72244949  1.66078330
## R077Q03  -0.28882109 0.2338051 -0.76062696  0.16475803
## R077Q04   0.10477463 0.2331784 -0.36454636  0.56132506
## R077Q05  -1.49362765 0.2344683 -1.96678566 -1.03244954
## R077Q06  -0.51496904 0.2328744 -0.98747207 -0.05882625
## R088Q01   0.48672640 0.2340617  0.02579410  0.93216518
## R088Q03  -1.25518607 0.2345156 -1.71629824 -0.78419679
## R088Q04T -2.66859130 0.2425514 -3.14059816 -2.17517339
## R088Q05T  0.59193270 0.2322848  0.12984963  1.04508942
## R088Q07   0.16368027 0.2331546 -0.30727166  0.61956514
## R110Q01   1.68979381 0.2381982  1.22226315  2.16384590
## R110Q04   1.61192325 0.2353119  1.13744931  2.07864456
## R110Q05   0.72861366 0.2340685  0.24731320  1.18613099
## R110Q06   1.06393856 0.2336769  0.61014419  1.52942376
## R216Q01   1.05985339 0.2361383  0.58760483  1.53604529
## R216Q02  -0.02689215 0.2314499 -0.49100467  0.42743751
## R216Q03T -0.76861139 0.2319565 -1.23360033 -0.30679440
## R216Q04  -0.95208793 0.2312141 -1.42218919 -0.49132385
## R216Q06   0.64384076 0.2317651  0.17220667  1.10892107
## R236Q01  -0.39272672 0.2319126 -0.86273541  0.05824742
## R236Q02  -1.91461940 0.2343319 -2.38893953 -1.45393891
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#ver la habilida estimada de cada estudiante }
\FunctionTok{ranef}\NormalTok{(modelo\_2pl)}\SpecialCharTok{$}\NormalTok{id}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## , , Intercept
## 
##         Estimate Est.Error        Q2.5         Q97.5
## 1     1.01050792 0.4573966  0.15472347  1.920069e+00
## 2     0.41942395 0.4252321 -0.39717429  1.268170e+00
## 3     2.66780092 0.6430480  1.49379320  4.007303e+00
## 4     2.29690366 0.5714150  1.25389140  3.452655e+00
## 5     1.44442071 0.4688770  0.56139375  2.385180e+00
## 6     3.13893228 0.7350793  1.78963023  4.689648e+00
## 7     0.04456147 0.4171937 -0.77711877  8.552898e-01
## 8     0.41410586 0.4311132 -0.41271150  1.272834e+00
## 9     0.99842053 0.4505144  0.12856838  1.881816e+00
## 10    0.22894603 0.4205136 -0.56486286  1.087338e+00
## 11    0.78876315 0.4533399 -0.07997335  1.677413e+00
## 12   -0.66638155 0.4320041 -1.51628539  1.601694e-01
## 13   -0.30971894 0.4039097 -1.11645781  4.935332e-01
## 14   -0.12705665 0.4144430 -0.94648187  6.962930e-01
## 15    1.00053546 0.4558538  0.14462282  1.914210e+00
## 16   -0.29809861 0.4245849 -1.11959456  5.351500e-01
## 17   -2.78417831 0.6212421 -4.12737416 -1.657972e+00
## 18    1.21886064 0.4738799  0.33142249  2.190337e+00
## 19   -0.47546499 0.4308202 -1.32780945  3.536670e-01
## 20    0.79467981 0.4545560 -0.07260327  1.709437e+00
## 21    1.00104984 0.4516773  0.17028019  1.884621e+00
## 22    1.21517999 0.4894810  0.30190089  2.222312e+00
## 23    1.98576789 0.5458112  0.98541539  3.112782e+00
## 24    1.21267899 0.4794946  0.29976630  2.224655e+00
## 25    0.04496495 0.4197865 -0.76458471  8.665138e-01
## 26   -0.65585944 0.4168364 -1.46577687  1.692602e-01
## 27    0.78737964 0.4475334 -0.06030947  1.703422e+00
## 28   -1.65385044 0.4899520 -2.66579016 -7.168799e-01
## 29   -3.21247761 0.7003048 -4.67463542 -1.948572e+00
## 30   -0.65843802 0.4317276 -1.50703104  1.948876e-01
## 31   -1.42368131 0.4591812 -2.37110155 -5.864620e-01
## 32    1.00227554 0.4465372  0.13393953  1.909205e+00
## 33    0.80432879 0.4603658 -0.11440689  1.749442e+00
## 34    0.04614834 0.4194619 -0.75879954  8.537401e-01
## 35   -0.12340033 0.4153132 -0.93302790  6.796784e-01
## 36   -0.29774799 0.4203024 -1.15635530  5.231492e-01
## 37   -0.30852776 0.4077410 -1.11558789  4.855212e-01
## 38   -0.65430928 0.4159795 -1.47328424  1.786440e-01
## 39   -1.02459581 0.4522035 -1.95135712 -1.726460e-01
## 40   -1.88603947 0.4900127 -2.88081888 -1.007847e+00
## 41    0.41055304 0.4404759 -0.43908296  1.269304e+00
## 42    1.21855724 0.4878017  0.30596121  2.236524e+00
## 43   -0.66236499 0.4393818 -1.52134587  1.958813e-01
## 44    0.59298296 0.4473138 -0.28122511  1.490878e+00
## 45    0.40341051 0.4541479 -0.49021883  1.342844e+00
## 46   -0.65165280 0.4249912 -1.49324868  1.685907e-01
## 47    0.78521539 0.4509419 -0.09233873  1.679024e+00
## 48    1.44790864 0.4986261  0.51488035  2.437545e+00
## 49   -0.83746562 0.4331456 -1.69894687 -5.734727e-03
## 50    0.22820910 0.4342985 -0.63294630  1.060598e+00
## 51    0.78992238 0.4423881 -0.04929347  1.701282e+00
## 52    0.05220502 0.4262297 -0.75277602  8.738243e-01
## 53    0.99367873 0.4623063  0.11743442  1.919038e+00
## 54    1.00215106 0.4576585  0.11872163  1.929961e+00
## 55   -0.11568862 0.4201295 -0.92985888  7.161324e-01
## 56    0.03699739 0.4243272 -0.76871808  8.599109e-01
## 57    1.00349158 0.4838729  0.09165942  1.987736e+00
## 58   -1.02437003 0.4539450 -1.91941877 -1.744107e-01
## 59    1.70204946 0.5059644  0.75417667  2.752921e+00
## 60   -0.66871249 0.4291020 -1.53502536  1.506070e-01
## 61    1.00287442 0.4646856  0.09336913  1.962101e+00
## 62   -1.21962659 0.4397611 -2.08787046 -3.754921e-01
## 63    1.21581588 0.4734052  0.31501589  2.193275e+00
## 64    1.98207814 0.5423483  0.97188996  3.086898e+00
## 65   -0.29429690 0.3990963 -1.07085873  4.835022e-01
## 66    1.69135528 0.5197306  0.70324468  2.770078e+00
## 67    1.44504711 0.4761823  0.53419311  2.440832e+00
## 68    0.78537732 0.4466134 -0.09364461  1.660584e+00
## 69    1.43839040 0.4776721  0.52288983  2.414435e+00
## 70    0.23086273 0.4225722 -0.56381179  1.066505e+00
## 71    1.21152301 0.4775468  0.31017406  2.129678e+00
## 72    1.98028632 0.5229589  1.00842603  3.046857e+00
## 73    0.99230983 0.4543548  0.13034957  1.919649e+00
## 74    1.70600355 0.5207213  0.73371498  2.771457e+00
## 75    0.05064183 0.4056453 -0.74315926  8.671438e-01
## 76    0.79278959 0.4506246 -0.06380665  1.689358e+00
## 77    1.21848580 0.4680189  0.32368651  2.132842e+00
## 78    1.44226434 0.4999891  0.50345762  2.437046e+00
## 79    0.21761245 0.4181940 -0.57191621  1.051246e+00
## 80   -0.13579929 0.4073338 -0.93382523  6.870576e-01
## 81   -1.02242934 0.4330169 -1.89484698 -2.119394e-01
## 82   -0.29884707 0.4081656 -1.06919413  4.903551e-01
## 83   -0.11809123 0.4217334 -0.94710904  7.186530e-01
## 84    0.60591426 0.4412265 -0.25011239  1.499342e+00
## 85   -0.11467473 0.4257750 -0.93796903  7.014667e-01
## 86   -0.30300746 0.4118821 -1.10322208  5.080479e-01
## 87    1.44812702 0.4871133  0.52963691  2.447665e+00
## 88    0.79317398 0.4479924 -0.07267946  1.698173e+00
## 89    0.59810349 0.4271726 -0.23415632  1.455195e+00
## 90    1.70588924 0.5341821  0.69388745  2.819217e+00
## 91    1.20329730 0.4821526  0.30737061  2.187148e+00
## 92    0.42282925 0.4255692 -0.38223241  1.282440e+00
## 93   -0.48444855 0.4264743 -1.34109737  3.429941e-01
## 94   -1.64392487 0.4753727 -2.62851598 -7.559445e-01
## 95   -0.29974984 0.4201137 -1.14299311  5.233975e-01
## 96    0.05055793 0.4173420 -0.76166541  8.757529e-01
## 97    0.59868031 0.4336287 -0.24025000  1.455397e+00
## 98    1.44304172 0.4766413  0.55759440  2.437784e+00
## 99    0.60444322 0.4443186 -0.25658356  1.498570e+00
## 100   1.21321347 0.4688873  0.32027468  2.152207e+00
## 101   0.99100839 0.4540981  0.12430290  1.908399e+00
## 102   0.79684914 0.4309382 -0.04208645  1.660758e+00
## 103   0.41079659 0.4387346 -0.42413428  1.304761e+00
## 104  -2.13697091 0.5246779 -3.21482189 -1.180437e+00
## 105  -1.03349870 0.4271068 -1.89557866 -1.926803e-01
## 106   0.79213339 0.4518752 -0.05245666  1.696866e+00
## 107  -1.22058534 0.4486071 -2.11995094 -3.525516e-01
## 108   1.44384508 0.4876400  0.53538288  2.447707e+00
## 109   0.59642631 0.4564594 -0.25735485  1.503971e+00
## 110   0.04855246 0.4250555 -0.76569047  9.100157e-01
## 111   0.41371928 0.4308007 -0.42010020  1.277449e+00
## 112   0.04975166 0.4278394 -0.79705130  9.160462e-01
## 113   1.45320886 0.4948144  0.52458919  2.430436e+00
## 114   0.59735010 0.4394640 -0.22191099  1.479974e+00
## 115   0.79178794 0.4473235 -0.07166005  1.707747e+00
## 116   1.44729858 0.4922981  0.50911949  2.434425e+00
## 117   1.22033391 0.4727966  0.33319099  2.174040e+00
## 118   1.20990419 0.4608299  0.34628791  2.148342e+00
## 119   0.77988628 0.4543650 -0.10715811  1.686314e+00
## 120   0.21944295 0.4389857 -0.61950474  1.080816e+00
## 121  -2.44721248 0.5693577 -3.63686584 -1.409626e+00
## 122  -0.48426902 0.4241624 -1.29546364  3.504740e-01
## 123   0.41176325 0.4291977 -0.39167512  1.263865e+00
## 124   1.44414678 0.4876760  0.54426780  2.435082e+00
## 125   0.78996396 0.4459081 -0.07579134  1.688741e+00
## 126   2.31373451 0.5970732  1.25057231  3.573581e+00
## 127   0.59038236 0.4392470 -0.26815682  1.502259e+00
## 128   0.80416058 0.4469855 -0.06115445  1.668775e+00
## 129   0.98996412 0.4599323  0.10031709  1.922409e+00
## 130  -1.88042348 0.5002812 -2.90731860 -9.500428e-01
## 131  -1.41548072 0.4549095 -2.33274552 -5.391254e-01
## 132  -1.41572128 0.4572916 -2.34044647 -5.530761e-01
## 133  -1.89574753 0.5062231 -2.90986172 -9.646517e-01
## 134  -1.88397966 0.5014153 -2.93385756 -9.536588e-01
## 135   0.79627684 0.4444513 -0.06505130  1.707449e+00
## 136   1.21927207 0.4766909  0.31913074  2.180005e+00
## 137   0.99960916 0.4574650  0.13749655  1.922173e+00
## 138   1.21254171 0.4684017  0.32092221  2.149107e+00
## 139   0.23694231 0.4297022 -0.59710520  1.118978e+00
## 140   0.04965117 0.4198202 -0.76670882  8.681703e-01
## 141   0.41889582 0.4336443 -0.42423433  1.272519e+00
## 142  -0.65556816 0.4354813 -1.52217748  2.080123e-01
## 143   1.44654078 0.4926161  0.53993503  2.453826e+00
## 144   2.30439102 0.5825892  1.25709900  3.521969e+00
## 145  -0.66344110 0.4421332 -1.56208428  1.867154e-01
## 146   0.23209772 0.4295119 -0.59716203  1.074542e+00
## 147  -1.21598728 0.4479828 -2.08255221 -3.608698e-01
## 148   1.97552049 0.5481524  0.97078345  3.089767e+00
## 149   1.69920248 0.5116831  0.76143188  2.752404e+00
## 150   1.21101082 0.4727690  0.31431766  2.159312e+00
## 151   1.45437220 0.5020805  0.50372019  2.506961e+00
## 152   1.98002618 0.5405536  0.99105467  3.087684e+00
## 153  -0.13421399 0.4224687 -0.99052961  6.791692e-01
## 154   0.40919693 0.4312058 -0.43209813  1.253561e+00
## 155  -2.13468385 0.5295769 -3.20403105 -1.155131e+00
## 156   0.04491211 0.4216323 -0.76615969  8.621278e-01
## 157   0.40547847 0.4451712 -0.44993657  1.328026e+00
## 158  -0.84221558 0.4202236 -1.67594163 -2.402756e-02
## 159  -1.89093894 0.4974892 -2.92755277 -9.554584e-01
## 160  -1.63898554 0.4786989 -2.60728520 -7.429357e-01
## 161  -1.43414261 0.4679565 -2.38709286 -5.565354e-01
## 162  -0.48307852 0.4237820 -1.30680223  3.218398e-01
## 163   0.05281477 0.4118885 -0.74235171  8.864644e-01
## 164   0.23281504 0.4289722 -0.59235147  1.095167e+00
## 165   1.21497726 0.4948980  0.27460622  2.217899e+00
## 166   1.20911711 0.4603146  0.31273421  2.138415e+00
## 167   1.20636824 0.4791418  0.30472692  2.157351e+00
## 168  -0.47421851 0.4255053 -1.32005593  3.752478e-01
## 169   0.04965003 0.3996952 -0.71552376  8.206997e-01
## 170   0.05092935 0.4159065 -0.76523338  8.893112e-01
## 171  -2.79091062 0.6225917 -4.09219830 -1.662879e+00
## 172  -1.64811756 0.4895619 -2.62633275 -7.290269e-01
## 173   1.44666194 0.4877549  0.52245588  2.447146e+00
## 174  -1.02336616 0.4464186 -1.90385960 -1.621322e-01
## 175  -0.13124840 0.4074492 -0.92378044  6.659575e-01
## 176  -1.03215484 0.4366852 -1.89679443 -1.794699e-01
## 177   0.22972796 0.4295601 -0.59852147  1.097734e+00
## 178   0.60343273 0.4355983 -0.23417168  1.464717e+00
## 179  -0.48151527 0.4126479 -1.29164856  3.128225e-01
## 180  -2.15088814 0.5210423 -3.20974991 -1.184723e+00
## 181  -1.42480301 0.4660878 -2.36443517 -5.339439e-01
## 182  -0.65494124 0.4259993 -1.49713467  1.838775e-01
## 183   0.04567683 0.4277266 -0.79954679  8.964324e-01
## 184  -1.22560747 0.4417781 -2.13740070 -4.014748e-01
## 185   0.40559544 0.4313084 -0.41313213  1.245528e+00
## 186   1.20966309 0.4747305  0.31161511  2.167485e+00
## 187   0.98757480 0.4589477  0.11015887  1.949027e+00
## 188   0.59961643 0.4351499 -0.22597516  1.465728e+00
## 189   0.41354304 0.4338940 -0.42820258  1.292662e+00
## 190   1.99152064 0.5428609  0.99553108  3.094011e+00
## 191   0.60358536 0.4359873 -0.24325788  1.479164e+00
## 192   1.01253306 0.4512552  0.15812466  1.918374e+00
## 193   1.98180498 0.5392475  0.96706083  3.134837e+00
## 194   1.70166923 0.5260665  0.75399081  2.776540e+00
## 195   0.99969912 0.4560319  0.14118053  1.938356e+00
## 196   1.98159634 0.5551004  0.95713797  3.152206e+00
## 197   1.21342113 0.4638526  0.32450760  2.160605e+00
## 198   1.20936425 0.4799767  0.29305979  2.196948e+00
## 199   1.00433019 0.4674418  0.09208864  1.951799e+00
## 200   2.29307273 0.5965169  1.20850407  3.550738e+00
## 201   1.21690823 0.4703212  0.32602320  2.176173e+00
## 202  -1.87680958 0.5000131 -2.88255569 -9.636341e-01
## 203   0.79331515 0.4453083 -0.07680970  1.679258e+00
## 204   0.22971155 0.4336687 -0.61213242  1.072532e+00
## 205  -0.66032234 0.4222408 -1.48841163  1.603001e-01
## 206  -0.65159700 0.4223467 -1.50473956  1.792566e-01
## 207   0.79743269 0.4507469 -0.06147707  1.734614e+00
## 208   0.99011749 0.4761895  0.10149421  1.968548e+00
## 209  -2.80895806 0.6156175 -4.11697595 -1.696908e+00
## 210  -2.43171938 0.5688012 -3.63594199 -1.399293e+00
## 211  -1.87927777 0.5055585 -2.91309490 -9.324346e-01
## 212  -1.02163278 0.4302055 -1.89883511 -1.934872e-01
## 213   0.78851645 0.4458131 -0.02257435  1.690312e+00
## 214   0.78950467 0.4464727 -0.07715678  1.648694e+00
## 215   1.44417250 0.5072955  0.48615020  2.462557e+00
## 216   0.23972410 0.4159142 -0.59186288  1.058557e+00
## 217   0.41279654 0.4237014 -0.40152315  1.261767e+00
## 218   0.41596053 0.4304202 -0.42799813  1.274041e+00
## 219   1.45761329 0.4889469  0.56577763  2.421260e+00
## 220  -0.12296100 0.4117218 -0.92604258  6.852705e-01
## 221   0.99901283 0.4662850  0.11981607  1.912155e+00
## 222   0.79001592 0.4439947 -0.05735175  1.675403e+00
## 223   0.59488745 0.4408935 -0.25241116  1.499188e+00
## 224   1.00237847 0.4735133  0.11415877  1.922739e+00
## 225   0.99742443 0.4622123  0.09822919  1.921698e+00
## 226   0.23506065 0.4246975 -0.55831657  1.075922e+00
## 227  -1.87973415 0.4764554 -2.88130412 -1.010270e+00
## 228  -1.02545996 0.4346691 -1.89872348 -1.807258e-01
## 229  -1.02281993 0.4270534 -1.86543151 -2.139136e-01
## 230  -3.21520622 0.6823506 -4.63953466 -1.985399e+00
## 231  -0.13001917 0.4160555 -0.95841250  6.904740e-01
## 232  -2.79095142 0.6126969 -4.07802856 -1.685961e+00
## 233  -0.29940693 0.4296626 -1.13891326  5.792376e-01
## 234   1.21491063 0.4819152  0.25899457  2.177249e+00
## 235   1.20688458 0.4765040  0.30432087  2.182313e+00
## 236   1.44402851 0.4908865  0.53797153  2.451256e+00
## 237   1.00315606 0.4496416  0.15490189  1.921337e+00
## 238   0.99508051 0.4594045  0.13399097  1.910503e+00
## 239   0.22651878 0.4237442 -0.58660692  1.078068e+00
## 240  -1.22128845 0.4456972 -2.10224903 -3.793788e-01
## 241   0.04964969 0.4132457 -0.74559627  8.676016e-01
## 242   0.40938934 0.4171712 -0.42339579  1.255754e+00
## 243  -1.21527490 0.4545734 -2.13501417 -3.429522e-01
## 244   1.44793466 0.4932513  0.50193702  2.467458e+00
## 245   1.21277509 0.4779983  0.28243887  2.206692e+00
## 246   1.00002601 0.4559472  0.11835890  1.921709e+00
## 247   1.21940541 0.4868174  0.28897484  2.202195e+00
## 248  -0.66153835 0.4331212 -1.51431558  2.034273e-01
## 249  -0.47715653 0.4183738 -1.28087128  3.238885e-01
## 250  -1.21602230 0.4503202 -2.12788254 -3.337337e-01
## 251   0.04938048 0.4232745 -0.78021717  8.908795e-01
## 252  -1.02410292 0.4405663 -1.92590502 -1.976130e-01
## 253  -0.66016294 0.4336198 -1.51524972  1.854253e-01
## 254  -0.47644489 0.4312406 -1.32776468  3.999063e-01
## 255  -2.14401942 0.5337825 -3.29642851 -1.158063e+00
## 256  -0.65294994 0.4375082 -1.54503391  2.131400e-01
## 257   0.04091047 0.4266098 -0.80212046  8.850115e-01
## 258  -1.21907760 0.4425150 -2.11792825 -3.506216e-01
## 259  -0.64890666 0.4333528 -1.50051806  1.950867e-01
## 260  -1.88638215 0.5020965 -2.91746872 -9.668847e-01
## 261   1.70172817 0.5183718  0.71673887  2.742599e+00
## 262   0.59609515 0.4226970 -0.21850342  1.478018e+00
## 263  -0.30235933 0.4324544 -1.18291359  5.653813e-01
## 264  -0.11557865 0.4205379 -0.94899452  7.009345e-01
## 265  -0.83921977 0.4383111 -1.71869123 -4.141056e-05
## 266  -1.41994704 0.4670555 -2.40371498 -5.263854e-01
## 267   1.21422395 0.4665929  0.34303839  2.130424e+00
## 268  -0.30064231 0.4225216 -1.12599891  5.425853e-01
## 269  -1.21585561 0.4449574 -2.12303468 -3.599112e-01
## 270  -1.65239937 0.4871942 -2.66915099 -7.192729e-01
## 271  -1.87987372 0.4898360 -2.87153319 -9.760592e-01
## 272  -2.14792168 0.5356673 -3.26119856 -1.164957e+00
## 273  -0.65903786 0.4257279 -1.50992481  1.902503e-01
## 274  -0.46789577 0.4265493 -1.29925786  3.678971e-01
## 275  -1.22922285 0.4464701 -2.12414551 -3.764363e-01
## 276  -0.31017936 0.4164411 -1.15196243  5.228128e-01
## 277  -1.02876707 0.4321497 -1.88959158 -2.087827e-01
## 278  -0.48924119 0.4099650 -1.31292992  2.986828e-01
## 279  -1.87744647 0.5071253 -2.91457389 -9.302629e-01
## 280  -1.87287107 0.4996361 -2.85167934 -9.018133e-01
## 281  -2.15111121 0.5542764 -3.31412788 -1.134107e+00
## 282  -1.88614895 0.4953179 -2.91828119 -9.699157e-01
## 283  -2.43365169 0.5664829 -3.61593209 -1.406576e+00
## 284  -2.43903295 0.5810196 -3.66166265 -1.396937e+00
## 285   2.29814041 0.5931950  1.20378093  3.547868e+00
## 286   3.12412350 0.7025081  1.88237020  4.622009e+00
## 287   1.21166651 0.4732099  0.29334619  2.183339e+00
## 288   1.71012348 0.5190354  0.74814713  2.788783e+00
## 289   0.98963237 0.4495043  0.13088587  1.895007e+00
## 290   1.44776412 0.4789321  0.56831012  2.404074e+00
## 291  -1.65062758 0.4634891 -2.55634719 -7.717506e-01
## 292  -0.29427953 0.4320539 -1.15236581  5.496251e-01
## 293  -0.66204560 0.4285785 -1.50071734  1.745852e-01
## 294  -0.83531956 0.4227109 -1.64759912 -1.954799e-02
## 295  -0.84695327 0.4338861 -1.72632764 -4.070271e-03
## 296  -1.22641940 0.4394254 -2.11140925 -3.799975e-01
## 297   0.60009016 0.4300396 -0.22143277  1.453935e+00
## 298   0.99790991 0.4579735  0.11085740  1.907132e+00
## 299  -0.65318365 0.4265964 -1.53622264  1.727922e-01
## 300   0.22517224 0.4397886 -0.65145643  1.111797e+00
## 301   0.59878167 0.4137074 -0.17326774  1.402870e+00
## 302   1.00263278 0.4651231  0.12004266  1.933898e+00
## 303   0.04353344 0.4197818 -0.77411402  8.804655e-01
## 304   0.03787893 0.4323898 -0.78557887  8.891410e-01
## 305   0.59905278 0.4379387 -0.25477022  1.482775e+00
## 306   0.23585791 0.4390839 -0.60847566  1.087143e+00
## 307   0.60010277 0.4246108 -0.20978756  1.451081e+00
## 308   1.00461605 0.4581731  0.13486734  1.922458e+00
## 309  -0.13147802 0.4250582 -0.96520128  7.210170e-01
## 310   0.05316055 0.4230971 -0.75020491  8.997236e-01
## 311   1.96963450 0.5462704  0.94477983  3.104653e+00
## 312   1.98781973 0.5559643  0.95095829  3.151743e+00
## 313   0.79364248 0.4343328 -0.02757179  1.652971e+00
## 314   1.71005880 0.5034951  0.76443670  2.716078e+00
## 315   1.20878304 0.4852562  0.29614596  2.210102e+00
## 316   0.22470734 0.4218006 -0.57678928  1.062937e+00
## 317   1.21617908 0.4696625  0.31174443  2.170646e+00
## 318   0.99962647 0.4675867  0.10890691  1.959867e+00
## 319   1.69981637 0.5121668  0.73173409  2.729901e+00
## 320   0.41085713 0.4347780 -0.41965431  1.284998e+00
## 321  -0.85171085 0.4539365 -1.72830895  2.643289e-02
## 322   0.98538184 0.4517537  0.12761332  1.903531e+00
## 323  -0.30267983 0.4199381 -1.12633257  5.206506e-01
## 324  -1.01875802 0.4320857 -1.88784170 -2.084288e-01
## 325  -1.64162834 0.4658712 -2.58289100 -7.659162e-01
## 326  -0.11922270 0.4140621 -0.93291259  6.945842e-01
## 327  -0.48196904 0.4341537 -1.34035173  3.539696e-01
## 328   0.23420634 0.4325204 -0.59201637  1.087822e+00
## 329  -1.22384962 0.4580227 -2.14823058 -3.363239e-01
## 330  -0.65310207 0.4198357 -1.50126816  1.723760e-01
## 331   0.40825415 0.4404439 -0.45037757  1.294094e+00
## 332   0.40942729 0.4414776 -0.43153706  1.294306e+00
## 333   1.00060036 0.4537587  0.13070552  1.896028e+00
## 334   0.40658671 0.4258157 -0.41953358  1.241480e+00
## 335   1.20677564 0.4698649  0.30710967  2.150547e+00
## 336  -1.02987049 0.4383423 -1.90077002 -2.177029e-01
## 337   0.23625517 0.4080728 -0.55709927  1.043898e+00
## 338  -0.30473002 0.4256226 -1.14263833  5.109185e-01
## 339  -2.14512544 0.5262912 -3.23299124 -1.161198e+00
## 340  -1.63877379 0.4721828 -2.60220510 -7.563616e-01
## 341  -1.22834833 0.4504413 -2.14080654 -3.579262e-01
## 342  -0.85097201 0.4417211 -1.70800629  3.194627e-03
## 343  -0.31145547 0.4188447 -1.14211148  5.153882e-01
## 344  -1.87527466 0.4981406 -2.91031279 -9.369697e-01
## 345   1.43527738 0.4784583  0.51142050  2.401729e+00
## 346   0.59700286 0.4424805 -0.24235797  1.494799e+00
## 347   1.70250555 0.5155415  0.74526770  2.766758e+00
## 348   1.21596718 0.4840774  0.28798216  2.179435e+00
## 349   0.79698592 0.4536559 -0.05691363  1.687131e+00
## 350   1.43876069 0.4832419  0.51629265  2.410937e+00
## 351  -2.43534552 0.5573323 -3.59753739 -1.414226e+00
## 352   1.20737847 0.4708473  0.33041062  2.174296e+00
## 353  -0.65311559 0.4195992 -1.47458985  1.529022e-01
## 354  -0.47954003 0.4262088 -1.35595245  3.554990e-01
## 355  -2.14051446 0.5158174 -3.22331401 -1.172692e+00
## 356  -1.87276640 0.4898428 -2.86484169 -9.267300e-01
## 357  -2.78732154 0.6027512 -4.06233569 -1.697560e+00
## 358  -0.84046756 0.4388096 -1.71347750  1.653315e-02
## 359   1.20942345 0.4867490  0.29327950  2.189220e+00
## 360  -0.83666545 0.4372759 -1.71313718  1.214416e-02
## 361  -1.22816733 0.4528939 -2.15880348 -3.658511e-01
## 362  -1.22427783 0.4463730 -2.11607016 -3.918259e-01
## 363  -2.14464537 0.5378444 -3.24240404 -1.159904e+00
## 364  -1.65194912 0.4825000 -2.63468533 -7.600919e-01
## 365   0.22402432 0.4214150 -0.58360745  1.073205e+00
## 366   1.00237027 0.4641235  0.11549427  1.938006e+00
## 367  -1.21927371 0.4434754 -2.10953228 -3.792235e-01
## 368  -0.48001256 0.4203126 -1.32651123  3.432041e-01
## 369   0.60731636 0.4331679 -0.22116478  1.477754e+00
## 370   0.79531203 0.4386180 -0.04307035  1.665985e+00
## 371   0.23847558 0.4274277 -0.58854510  1.101909e+00
## 372  -0.66525378 0.4326322 -1.54102160  1.662549e-01
## 373  -0.48489662 0.4195675 -1.31479807  3.244346e-01
## 374   1.00506669 0.4675148  0.12607021  1.935660e+00
## 375   0.23403748 0.4245006 -0.56594838  1.078018e+00
## 376   1.21465279 0.4787586  0.30164172  2.185379e+00
## 377   0.79425521 0.4418067 -0.07083854  1.707066e+00
## 378  -0.66569872 0.4270833 -1.50628209  1.586057e-01
## 379   0.78882528 0.4513140 -0.04537081  1.719533e+00
## 380  -1.43087851 0.4686269 -2.35213076 -5.591019e-01
## 381  -1.42827278 0.4619869 -2.35468364 -5.585898e-01
## 382   0.05153796 0.4265570 -0.77555287  8.961596e-01
## 383   1.21511699 0.4715089  0.32791312  2.170659e+00
## 384  -1.21718532 0.4618648 -2.15315397 -3.567567e-01
## 385   1.97411485 0.5320193  0.97060890  3.043084e+00
## 386   0.60235517 0.4315010 -0.23705302  1.463151e+00
## 387  -1.42985951 0.4579654 -2.35805700 -5.785925e-01
## 388   0.60861517 0.4571270 -0.26059503  1.528586e+00
## 389  -0.12255670 0.4272305 -0.96575452  7.087523e-01
## 390  -1.02712256 0.4356811 -1.89390032 -1.705988e-01
## 391  -0.12746330 0.4152430 -0.91939040  7.122102e-01
## 392  -2.44849118 0.5650409 -3.65340461 -1.438190e+00
## 393  -2.12665512 0.5205452 -3.19633979 -1.151683e+00
## 394   0.59046159 0.4368261 -0.24596015  1.456363e+00
## 395   0.05079858 0.4157389 -0.75436043  8.766061e-01
## 396  -1.41883759 0.4556365 -2.30767621 -5.413955e-01
## 397   2.66821810 0.6263833  1.50543074  3.980777e+00
## 398   0.05425051 0.4258482 -0.76728304  8.990670e-01
## 399   1.70405480 0.5148280  0.74564147  2.762803e+00
## 400  -0.83556598 0.4392150 -1.74000022  1.166103e-02
## 401  -0.83155783 0.4359940 -1.69393271  5.383673e-03
## 402  -1.43567531 0.4617395 -2.39620348 -5.507443e-01
## 403   0.22605933 0.4362551 -0.63617496  1.105125e+00
## 404  -1.42924441 0.4640106 -2.35654447 -5.598198e-01
## 405   1.43464022 0.4749559  0.53385729  2.392230e+00
## 406   0.41773968 0.4332486 -0.40077442  1.278310e+00
## 407   1.70851581 0.5137592  0.75280011  2.739352e+00
## 408   1.44399249 0.4832573  0.51801978  2.413917e+00
## 409   0.60207632 0.4506440 -0.26182077  1.485827e+00
## 410   1.70967514 0.5289824  0.71376496  2.805414e+00
## 411  -2.14170811 0.5378771 -3.28118424 -1.148566e+00
## 412  -0.65893151 0.4282475 -1.47889808  1.845068e-01
## 413  -0.31173427 0.4188918 -1.14083600  5.070663e-01
## 414   0.05249723 0.4187592 -0.78693465  9.036545e-01
## 415  -0.13114533 0.4229141 -0.93899628  6.829301e-01
## 416  -1.21481507 0.4443621 -2.12362200 -3.767473e-01
## 417  -0.83152297 0.4254479 -1.68076356 -2.752167e-02
## 418  -2.44587590 0.5667043 -3.59373059 -1.396154e+00
## 419  -0.49056242 0.4246501 -1.32258661  3.492627e-01
## 420  -0.47313750 0.4325819 -1.30677904  3.736472e-01
## 421  -1.42150680 0.4679322 -2.37959750 -5.260128e-01
## 422  -1.21406361 0.4586899 -2.13850497 -3.443269e-01
## 423   0.79755853 0.4619517 -0.07715159  1.752291e+00
## 424  -1.02695129 0.4280210 -1.88285185 -2.033211e-01
## 425  -1.43498074 0.4721933 -2.35942598 -5.412869e-01
## 426   0.22963141 0.4292629 -0.61135177  1.073432e+00
## 427   0.23416905 0.4292075 -0.60420195  1.098094e+00
## 428  -0.31181296 0.4090593 -1.11278826  4.818618e-01
## 429   0.59888433 0.4340339 -0.23169317  1.467144e+00
## 430   0.40673767 0.4166666 -0.40905127  1.224196e+00
## 431  -0.66522665 0.4145938 -1.46510588  1.164036e-01
## 432  -0.47560513 0.4260080 -1.30637941  3.489448e-01
## 433  -0.30476963 0.4198521 -1.12913860  5.060333e-01
## 434   1.43647535 0.4833353  0.50463132  2.456243e+00
## 435  -0.83643810 0.4375277 -1.71287918 -5.594081e-03
## 436   0.23321263 0.4271844 -0.59019720  1.072378e+00
## 437   1.97790265 0.5601998  0.93812988  3.155332e+00
## 438   0.59731142 0.4342180 -0.24471492  1.470572e+00
## 439   1.69795390 0.5133576  0.75110073  2.756929e+00
## 440   0.40703462 0.4309324 -0.41244649  1.251558e+00
## 441   1.44621512 0.5080892  0.50101240  2.443629e+00
## 442   1.97814320 0.5396355  0.98577738  3.117306e+00
## 443   0.77703477 0.4359602 -0.06971615  1.651716e+00
## 444   1.45226313 0.4903877  0.53019286  2.461626e+00
## 445  -1.03716957 0.4298461 -1.87386689 -2.065982e-01
## 446   0.22937686 0.4270967 -0.60187743  1.059345e+00
## 447   0.04797367 0.4264681 -0.79155738  8.806413e-01
## 448  -0.30189109 0.4058096 -1.06751633  4.978983e-01
## 449  -0.13474732 0.4183367 -0.95908243  6.790318e-01
## 450  -0.46525700 0.4111173 -1.25167807  3.358520e-01
## 451   0.40066061 0.4185360 -0.41749886  1.232410e+00
## 452   0.79085755 0.4510487 -0.05590414  1.703119e+00
## 453   0.59793804 0.4341943 -0.22405006  1.474231e+00
## 454  -2.14312328 0.5239239 -3.26532889 -1.181598e+00
## 455  -1.22387786 0.4579635 -2.10834872 -3.328252e-01
## 456   1.21561967 0.4761497  0.33776432  2.178415e+00
## 457   1.21295312 0.4615677  0.33337097  2.157939e+00
## 458   0.22650081 0.4181969 -0.57902920  1.054980e+00
## 459   1.45222996 0.4928938  0.54093845  2.460336e+00
## 460  -0.83909967 0.4256940 -1.67384635 -1.707421e-02
## 461   2.30724564 0.5956801  1.18727356  3.564861e+00
## 462   0.23673922 0.4209761 -0.59212551  1.095522e+00
## 463   1.21043779 0.4611140  0.34795215  2.146198e+00
## 464   0.99919423 0.4551828  0.14054003  1.904174e+00
## 465  -0.84452340 0.4245949 -1.71842660 -7.726168e-03
## 466  -0.48395793 0.4177061 -1.29281705  3.253842e-01
## 467  -0.31026224 0.4304007 -1.15100819  5.311514e-01
## 468   1.69725981 0.5040356  0.75884786  2.733928e+00
## 469   1.00169013 0.4581288  0.13262223  1.945452e+00
## 470   2.30903534 0.5980826  1.19227659  3.534204e+00
## 471   0.99878010 0.4501537  0.13793235  1.912587e+00
## 472   1.98187705 0.5360292  0.99477254  3.101950e+00
## 473   1.21335265 0.4785736  0.31442908  2.169259e+00
## 474   0.40202006 0.4376879 -0.44740337  1.281845e+00
## 475  -0.84069344 0.4324365 -1.67468207  1.607234e-02
## 476  -2.78555322 0.6063672 -4.11411487 -1.695586e+00
## 477  -0.65820915 0.4259970 -1.47065733  1.666968e-01
## 478  -0.84015482 0.4278807 -1.70124688  1.677668e-03
## 479   0.59724969 0.4438364 -0.25284007  1.487236e+00
## 480  -1.88307154 0.5161544 -2.89442639 -9.231172e-01
## 481  -0.66545023 0.4290619 -1.51530582  1.668638e-01
## 482  -1.42135228 0.4567950 -2.33922319 -5.651489e-01
## 483   0.40019274 0.4319151 -0.43489270  1.276846e+00
## 484  -0.12490339 0.4102981 -0.93945423  6.850541e-01
## 485   0.22590632 0.4168699 -0.56371296  1.044334e+00
## 486   0.99192317 0.4392469  0.17638220  1.860567e+00
## 487  -0.65432628 0.4174413 -1.50128457  1.784323e-01
## 488  -0.11975481 0.4213360 -0.92703950  6.936247e-01
## 489   0.04178973 0.4115169 -0.76786305  8.324325e-01
## 490  -1.42883345 0.4557116 -2.37531645 -5.830062e-01
## 491   0.79443094 0.4514030 -0.08577123  1.695770e+00
## 492   0.23536148 0.4243491 -0.59726549  1.094677e+00
## 493  -0.29803779 0.4335880 -1.15831726  5.558245e-01
## 494  -1.22373057 0.4396192 -2.10787362 -3.881208e-01
## 495  -0.84188609 0.4459423 -1.74256408  3.152157e-02
## 496  -0.83503808 0.4222521 -1.66442072 -5.227592e-02
## 497   0.04677545 0.4191415 -0.76818857  8.785092e-01
## 498   1.45921132 0.4903819  0.51749159  2.444198e+00
## 499   0.03983504 0.4271728 -0.77807162  8.886910e-01
## 500   1.45126208 0.4897261  0.52523017  2.435133e+00
## 501  -1.65408777 0.4699956 -2.63312701 -7.788148e-01
## 502  -1.88988482 0.4968446 -2.90777196 -9.560938e-01
## 503  -0.84673136 0.4256387 -1.70039579 -8.088469e-03
## 504  -1.64457881 0.4648795 -2.58493056 -7.570121e-01
## 505  -0.83141656 0.4201890 -1.65622956 -3.268954e-02
## 506  -0.84609634 0.4287656 -1.71898488 -2.762705e-02
## 507   0.40678158 0.4311388 -0.41458644  1.254333e+00
## 508  -1.42372879 0.4505346 -2.31790821 -5.899579e-01
## 509   0.04998579 0.4175819 -0.77033648  8.840401e-01
## 510  -0.65766054 0.4256599 -1.49866752  1.610154e-01
## 511   0.04160916 0.4256438 -0.77041743  9.125779e-01
## 512  -0.65881314 0.4327556 -1.52063745  2.054409e-01
## 513  -0.65863652 0.4247581 -1.51376084  1.662597e-01
## 514  -0.67111576 0.4372098 -1.55836131  1.682207e-01
## 515  -1.21438723 0.4543474 -2.13980218 -3.689771e-01
## 516  -0.46943060 0.4339494 -1.32045355  3.665441e-01
## 517   0.05618990 0.4246997 -0.74934188  9.090358e-01
## 518  -1.65072017 0.4771716 -2.61019929 -7.244553e-01
## 519  -1.41621761 0.4476478 -2.35327632 -5.705246e-01
## 520  -0.83611844 0.4203633 -1.67327608 -5.042915e-02
## 521  -0.84398979 0.4223792 -1.67134945 -1.395874e-02
## 522   0.41038684 0.4432862 -0.46563419  1.301621e+00
## 523  -0.30219687 0.4204114 -1.12595814  5.155214e-01
## 524   1.00084196 0.4649542  0.11799814  1.959260e+00
## 525   0.79486866 0.4458618 -0.04340937  1.719241e+00
## 526   1.70020623 0.5176833  0.72632498  2.749889e+00
## 527  -0.12977664 0.3968165 -0.90885755  6.345676e-01
## 528   0.23590091 0.4259026 -0.58577084  1.096930e+00
## 529  -1.22606097 0.4484151 -2.11608797 -3.774827e-01
## 530  -1.01327719 0.4271955 -1.90772137 -1.811361e-01
## 531   1.21549760 0.4812849  0.31401311  2.183196e+00
## 532  -0.30328227 0.4267308 -1.13286673  5.309852e-01
## 533   0.59744851 0.4343238 -0.23734661  1.483108e+00
## 534  -0.65731132 0.4306723 -1.50240818  1.945320e-01
## 535   0.22719177 0.4300894 -0.60963446  1.075513e+00
## 536   0.78870535 0.4508745 -0.05421006  1.710008e+00
## 537   1.44850898 0.4755575  0.55668529  2.396679e+00
## 538   0.40946147 0.4309846 -0.43599327  1.255741e+00
## 539  -1.64539147 0.4857355 -2.63244488 -7.279685e-01
## 540   2.29242380 0.5688393  1.22899878  3.456764e+00
## 541   0.99759036 0.4632046  0.13164316  1.949463e+00
## 542   0.99788222 0.4637819  0.10082605  1.927228e+00
## 543   1.97834994 0.5548321  0.95006988  3.145671e+00
## 544   0.22937421 0.4294901 -0.61922604  1.100728e+00
## 545   0.79607766 0.4454764 -0.07912754  1.691345e+00
## 546  -0.14124479 0.4204040 -0.97259649  6.988071e-01
## 547  -0.47681104 0.4118961 -1.29017040  3.167746e-01
## 548   1.98027243 0.5510596  0.95880323  3.113135e+00
## 549   0.23386968 0.4170941 -0.57294601  1.061257e+00
## 550   1.46056976 0.5046617  0.53715450  2.488270e+00
## 551   1.00063986 0.4542264  0.14088540  1.918721e+00
## 552   1.68558139 0.5045868  0.74573597  2.714738e+00
## 553  -0.48349427 0.4210583 -1.31432802  3.340491e-01
## 554   1.69249741 0.5115992  0.74231812  2.737150e+00
## 555   1.97521930 0.5419673  0.97316140  3.069546e+00
## 556   0.79069335 0.4370657 -0.03648162  1.685628e+00
## 557   2.68261858 0.6496301  1.48365992  4.055566e+00
## 558  -1.65369140 0.4845811 -2.64437281 -7.603226e-01
## 559  -1.01909283 0.4343598 -1.89667240 -1.888202e-01
## 560  -1.42442731 0.4605272 -2.37911950 -5.436997e-01
## 561  -1.88426279 0.5145225 -2.94218921 -9.233485e-01
## 562  -1.22443834 0.4403676 -2.10247793 -3.748410e-01
## 563  -1.88202412 0.4928813 -2.90750619 -9.588590e-01
## 564   0.05278728 0.4171905 -0.75770882  8.941163e-01
## 565  -0.66352804 0.4244865 -1.49087992  1.686438e-01
## 566  -1.64199769 0.4622782 -2.57284541 -7.857428e-01
## 567  -2.15404674 0.5339507 -3.28621433 -1.188223e+00
## 568  -0.12607388 0.4178936 -0.94050864  6.937810e-01
## 569   1.01001044 0.4468442  0.18474882  1.922090e+00
## 570   0.58768627 0.4426446 -0.27447993  1.444998e+00
## 571  -0.13093675 0.4118854 -0.93769791  6.686107e-01
## 572   0.79928497 0.4539487 -0.07338606  1.705189e+00
## 573   0.23039550 0.4221294 -0.58245351  1.035324e+00
## 574  -0.13935519 0.4160514 -0.96990035  6.721373e-01
## 575   1.97935353 0.5531163  0.93953293  3.146282e+00
## 576   1.99001521 0.5526041  0.95135169  3.113707e+00
## 577   1.20962246 0.4697478  0.32835367  2.144053e+00
## 578   0.42819749 0.4133266 -0.38677797  1.251047e+00
## 579   0.59049918 0.4154698 -0.20593149  1.396128e+00
## 580  -0.30455646 0.4014283 -1.10253039  4.730203e-01
## 581  -0.48203672 0.4107091 -1.28884079  3.092325e-01
## 582  -1.63880730 0.4718644 -2.60831330 -7.660214e-01
## 583  -1.88180634 0.4887302 -2.86777994 -9.652984e-01
## 584   0.59942853 0.4353092 -0.24841790  1.486617e+00
## 585  -1.21598204 0.4483444 -2.13611413 -3.504334e-01
## 586   0.78987339 0.4485243 -0.08347560  1.687983e+00
## 587  -1.41818241 0.4699098 -2.38864221 -5.272462e-01
## 588  -1.42882767 0.4472887 -2.33803416 -5.790391e-01
## 589  -1.02784413 0.4453345 -1.90716099 -1.678911e-01
## 590  -2.14079883 0.5245244 -3.21107434 -1.175033e+00
## 591   0.05451736 0.4185224 -0.79450169  8.728528e-01
## 592  -1.42443194 0.4639340 -2.38573625 -5.264130e-01
## 593   1.97993293 0.5541723  0.96205264  3.131699e+00
## 594   0.59898238 0.4428033 -0.26104942  1.472280e+00
## 595   0.41117050 0.4475539 -0.45237693  1.289188e+00
## 596  -0.46989824 0.4180537 -1.29241535  3.290848e-01
## 597  -0.46746487 0.4161564 -1.26579275  3.333572e-01
## 598  -1.22256759 0.4508705 -2.13131572 -3.630697e-01
## 599  -1.42172339 0.4663471 -2.36196068 -5.377898e-01
## 600   0.78634484 0.4249321 -0.01750172  1.637403e+00
## 601   0.22670155 0.4409489 -0.62257119  1.104620e+00
## 602   1.21550475 0.4788711  0.29776276  2.194169e+00
## 603   0.40069894 0.4220018 -0.42666131  1.228130e+00
## 604   1.70153285 0.5237363  0.71784609  2.781122e+00
## 605   1.69368462 0.5133782  0.74896595  2.766833e+00
## 606   0.04191348 0.4014756 -0.73812755  8.209303e-01
## 607  -0.30873737 0.4358990 -1.16592430  5.447965e-01
## 608   0.77693132 0.4271939 -0.04258147  1.648445e+00
## 609   0.05594914 0.4212466 -0.77205519  9.065375e-01
## 610   1.00251078 0.4550409  0.15034499  1.896628e+00
## 611  -0.83955298 0.4365745 -1.74941341  5.215035e-03
## 612  -0.47480719 0.4163681 -1.29409820  3.261117e-01
## 613   0.40171028 0.4321372 -0.44991767  1.291015e+00
## 614  -1.64425430 0.4876751 -2.63453713 -7.027979e-01
## 615   0.78566418 0.4392264 -0.05114641  1.687685e+00
## 616   1.44508390 0.4860336  0.51952316  2.391784e+00
## 617   0.78850946 0.4499091 -0.08742549  1.668496e+00
## 618  -0.66155944 0.4243360 -1.49856708  1.402340e-01
## 619   1.70755132 0.5312631  0.71167189  2.799457e+00
## 620   0.59317323 0.4363380 -0.23020749  1.472119e+00
## 621  -0.31383408 0.4102097 -1.13037213  4.925810e-01
## 622   1.98056658 0.5550830  0.93896419  3.115180e+00
## 623   1.45198603 0.4716504  0.58604127  2.376580e+00
## 624   0.79930528 0.4506279 -0.06251753  1.696087e+00
## 625   1.45365352 0.4889411  0.52862439  2.468776e+00
## 626   0.22742531 0.4320724 -0.62526380  1.063902e+00
## 627   0.23470953 0.4185156 -0.59410379  1.068582e+00
## 628   0.22447108 0.4203348 -0.55539147  1.080247e+00
## 629  -0.84452367 0.4253135 -1.71356114 -2.317828e-02
## 630  -1.64536593 0.4754285 -2.62190053 -7.480424e-01
## 631   0.99254204 0.4624271  0.11605725  1.927338e+00
## 632  -0.30994315 0.4281448 -1.14766927  5.127100e-01
## 633  -0.29961033 0.4071424 -1.11222214  5.008400e-01
## 634   0.23612904 0.4338989 -0.58333502  1.092241e+00
## 635  -0.47785925 0.4128188 -1.28570944  3.260112e-01
## 636   0.80220085 0.4432596 -0.02664780  1.676215e+00
## 637   2.29483627 0.5922632  1.22259101  3.508239e+00
## 638   0.40597421 0.4421945 -0.44468361  1.289240e+00
## 639   1.44350954 0.4968429  0.51481637  2.475562e+00
## 640   2.31308639 0.5845663  1.23821450  3.500565e+00
## 641   1.70557044 0.5334566  0.69517353  2.795337e+00
## 642  -1.43418250 0.4604355 -2.39419948 -5.888537e-01
## 643  -1.22431915 0.4519752 -2.12276633 -3.674660e-01
## 644  -0.48115413 0.4168498 -1.29899917  3.213114e-01
## 645  -1.02546549 0.4414328 -1.89638663 -1.913024e-01
## 646   0.05272647 0.4208669 -0.78504230  8.925784e-01
## 647   0.41567708 0.4345642 -0.42839733  1.278205e+00
## 648  -1.02999580 0.4294156 -1.89548826 -2.218332e-01
## 649  -1.04022972 0.4413281 -1.90016899 -2.070632e-01
## 650   0.59547517 0.4431895 -0.26118830  1.488368e+00
## 651  -0.84742059 0.4350717 -1.71100214 -2.197968e-02
## 652  -0.47761541 0.4190369 -1.29053975  3.547700e-01
## 653  -1.87051842 0.5039681 -2.87490956 -9.430595e-01
## 654   0.40278924 0.4406332 -0.45034818  1.285776e+00
## 655  -1.43410997 0.4757694 -2.39363604 -5.548392e-01
## 656  -2.42619243 0.5681200 -3.59814572 -1.384220e+00
## 657  -1.41752264 0.4415147 -2.32193550 -5.854171e-01
## 658  -0.83000716 0.4265571 -1.66448285 -1.138144e-02
## 659  -0.65416906 0.4315503 -1.49247235  1.645411e-01
## 660  -1.42537384 0.4617202 -2.38032807 -5.312387e-01
## 661  -2.43796285 0.5510724 -3.56466913 -1.423224e+00
## 662  -1.22268691 0.4433956 -2.08610959 -3.779481e-01
## 663  -2.79751056 0.6297103 -4.11834044 -1.650509e+00
## 664  -1.64895777 0.4736379 -2.61958301 -7.560795e-01
## 665  -1.42031072 0.4601546 -2.33142226 -5.460770e-01
## 666  -2.79103054 0.6202756 -4.08801047 -1.650387e+00
## 667  -1.21926795 0.4444730 -2.08766989 -3.692435e-01
## 668  -1.65236280 0.4808249 -2.60585011 -7.597235e-01
## 669  -1.64823939 0.4737430 -2.62586248 -7.607491e-01
## 670   0.41023169 0.4333120 -0.42419354  1.258720e+00
## 671   0.41587313 0.4326711 -0.43037024  1.282672e+00
## 672  -1.43672665 0.4573850 -2.35724039 -5.657578e-01
## 673  -0.12799255 0.4185836 -0.92670621  6.897313e-01
## 674  -0.84367989 0.4423208 -1.73594788  1.630049e-02
## 675   1.70357581 0.5193880  0.72219646  2.747589e+00
## 676   0.99832304 0.4571354  0.14913278  1.916893e+00
## 677  -0.13440759 0.4144801 -0.92553276  6.864697e-01
## 678   1.00028162 0.4556914  0.12855562  1.939574e+00
## 679   1.69506028 0.5114163  0.71685872  2.762548e+00
## 680  -0.30427991 0.4129164 -1.11308955  4.976905e-01
## 681   1.70690277 0.5112987  0.75977042  2.700093e+00
## 682   0.99166342 0.4446575  0.15897255  1.899525e+00
## 683   0.22703242 0.4249289 -0.59295752  1.058894e+00
## 684   1.69663617 0.5169302  0.73402432  2.742717e+00
## 685   0.41533386 0.4308554 -0.42839032  1.267608e+00
## 686   0.78894314 0.4436019 -0.04930399  1.682230e+00
## 687   0.04738262 0.4167903 -0.76888824  8.706938e-01
## 688   0.39814466 0.4326724 -0.43264413  1.277391e+00
## 689   1.69388297 0.5187335  0.73472786  2.772262e+00
## 690  -0.66177342 0.4245675 -1.48464656  1.694404e-01
## 691  -0.65104272 0.4198614 -1.47814143  1.696666e-01
## 692  -1.21646235 0.4584447 -2.14208101 -3.542065e-01
## 693  -1.02100663 0.4294160 -1.90312452 -1.990392e-01
## 694  -2.14906701 0.5167382 -3.23049106 -1.187242e+00
## 695   0.22256037 0.4177411 -0.57681686  1.062833e+00
## 696  -0.30160880 0.4101027 -1.11089971  5.230884e-01
## 697  -1.89572512 0.5174306 -2.95775815 -9.334408e-01
## 698  -1.63212241 0.4850243 -2.63916192 -7.375512e-01
## 699  -0.30133326 0.4268155 -1.14275667  5.227014e-01
## 700  -0.83231703 0.4319085 -1.68454703 -7.926992e-04
## 701  -0.48602590 0.4319125 -1.34208670  3.635876e-01
## 702  -1.21996397 0.4473104 -2.12837509 -3.489894e-01
## 703  -0.11977821 0.4117156 -0.92464370  6.773832e-01
## 704   0.22716400 0.4169322 -0.57811690  1.030993e+00
## 705  -0.84217591 0.4376185 -1.72230396  5.724304e-03
## 706   1.70210301 0.5065064  0.76847547  2.688939e+00
## 707   1.97926587 0.5425506  0.96543388  3.129102e+00
## 708   1.00360139 0.4746650  0.08737742  1.984295e+00
## 709  -0.29756877 0.4189342 -1.12708642  4.965545e-01
## 710   0.99853753 0.4715038  0.10392952  1.934726e+00
## 711  -0.48330028 0.4228776 -1.32522228  3.530885e-01
## 712  -1.21693294 0.4500944 -2.13156197 -3.525213e-01
## 713  -1.42621468 0.4674263 -2.38537970 -5.460426e-01
## 714  -0.30046874 0.4309729 -1.15301232  5.469182e-01
## 715  -1.22526606 0.4418052 -2.13306043 -3.937088e-01
## 716  -1.64456728 0.4793213 -2.61315429 -7.779251e-01
## 717   0.79508921 0.4591884 -0.09170438  1.714994e+00
## 718  -0.65856482 0.4268995 -1.52469769  1.705390e-01
## 719   0.78929013 0.4339277 -0.04059491  1.649381e+00
## 720   1.20430308 0.4761883  0.28639179  2.141590e+00
## 721   1.23097943 0.4750806  0.32995586  2.189105e+00
## 722  -2.14369152 0.5277669 -3.21996480 -1.186927e+00
## 723  -0.12532450 0.4215354 -0.93004375  6.765377e-01
## 724   0.22980898 0.4149090 -0.55804439  1.050581e+00
## 725  -1.42386017 0.4512459 -2.33114527 -5.773535e-01
## 726  -0.29665578 0.4160413 -1.10252313  5.437491e-01
## 727  -1.42025966 0.4547975 -2.32889006 -5.692137e-01
## 728  -1.88498630 0.5067292 -2.94183906 -9.333013e-01
## 729   0.41382934 0.4191082 -0.40339292  1.245463e+00
## 730  -1.64175555 0.4794963 -2.62598328 -7.615392e-01
## 731  -1.02856684 0.4325150 -1.89700060 -1.957465e-01
## 732  -0.47408611 0.4253076 -1.29966021  3.479041e-01
## 733   0.23289176 0.4278503 -0.57334717  1.096484e+00
## 734   0.59637487 0.4337040 -0.23868841  1.458744e+00
## 735   0.04434542 0.4138621 -0.75356931  8.476241e-01
## 736  -1.21463032 0.4471991 -2.12435982 -3.711090e-01
## 737  -0.12453421 0.4372346 -0.98257181  7.350390e-01
## 738   1.45471460 0.4898718  0.52914074  2.463472e+00
## 739  -0.12595920 0.4274063 -0.96467246  7.353275e-01
## 740  -1.63951533 0.4775829 -2.62309919 -7.404115e-01
## 741  -0.30773163 0.4277965 -1.15937360  5.205351e-01
## 742   0.59320260 0.4412812 -0.24325969  1.438820e+00
## 743   2.30887983 0.5953781  1.21590424  3.605234e+00
## 744   1.21400228 0.4730857  0.29372029  2.165482e+00
## 745  -0.48241135 0.4248334 -1.31645594  3.595385e-01
## 746   0.23256932 0.4262814 -0.59332347  1.072587e+00
## 747   0.21996679 0.4174967 -0.59228816  1.037430e+00
## 748   0.05647747 0.4128054 -0.76014854  8.715323e-01
## 749   0.05255442 0.4238282 -0.74190210  8.868253e-01
## 750  -0.12503265 0.4222526 -0.94286541  6.984740e-01
## 751  -1.22817259 0.4600381 -2.14368025 -3.289105e-01
## 752   0.04242783 0.4330182 -0.82059275  8.966472e-01
## 753  -1.22466343 0.4367866 -2.11089013 -3.916046e-01
## 754   1.22325836 0.4730824  0.32455826  2.200544e+00
## 755  -0.48560216 0.4141034 -1.30093690  3.170542e-01
## 756  -0.11499560 0.4258673 -0.95256310  7.172231e-01
## 757  -0.30393975 0.4225615 -1.11445641  5.333921e-01
## 758   0.40271894 0.4299024 -0.41995647  1.257974e+00
## 759   0.59450263 0.4421957 -0.24589048  1.484480e+00
## 760   0.78872499 0.4651506 -0.09305385  1.709396e+00
## 761   0.77772022 0.4421954 -0.06282712  1.664163e+00
## 762   0.99827746 0.4616915  0.12912610  1.946857e+00
## 763   1.00111288 0.4635897  0.14254488  1.956493e+00
## 764  -0.29820142 0.4226849 -1.16355120  5.164864e-01
## 765   1.71188722 0.5324600  0.76088231  2.824610e+00
## 766   0.99394042 0.4564510  0.13760291  1.954693e+00
## 767   1.98323401 0.5482795  0.95588774  3.127796e+00
## 768   1.01160012 0.4626162  0.12279762  1.954806e+00
## 769   1.69898376 0.5178507  0.73523577  2.779125e+00
## 770   1.69415134 0.5297033  0.69591503  2.806621e+00
## 771   1.44703226 0.4919475  0.53776346  2.471133e+00
## 772   0.79888853 0.4457059 -0.06409449  1.671145e+00
## 773   1.96820362 0.5334491  0.97383683  3.087708e+00
## 774   1.96835275 0.5569374  0.90955036  3.121307e+00
## 775   0.60353940 0.4398783 -0.26585526  1.482528e+00
## 776   2.28422729 0.5954264  1.20337660  3.518713e+00
## 777   1.69965906 0.5198739  0.70835101  2.738292e+00
## 778   1.71061395 0.5182839  0.74588153  2.771408e+00
## 779   0.60091947 0.4426841 -0.26191623  1.471934e+00
## 780   0.41396618 0.4359687 -0.41866380  1.309104e+00
## 781   3.14370230 0.7310532  1.84221970  4.676724e+00
## 782   0.23257974 0.4379317 -0.60236013  1.093418e+00
## 783   0.99147287 0.4618284  0.10947331  1.909710e+00
## 784   1.69619702 0.5011000  0.75323633  2.748408e+00
## 785   0.59845567 0.4398451 -0.22467425  1.481673e+00
## 786   2.30881792 0.6044773  1.22338327  3.526953e+00
## 787   0.59397240 0.4544932 -0.28801729  1.490256e+00
## 788  -0.66499728 0.4409589 -1.52458570  2.058062e-01
## 789  -0.48793515 0.4232326 -1.31675484  3.406615e-01
## 790  -0.85103899 0.4252308 -1.68339109 -3.480961e-02
## 791  -0.30524724 0.4197471 -1.12414644  5.133568e-01
## 792   0.41052409 0.4223051 -0.39575513  1.260587e+00
## 793   0.41410330 0.4423871 -0.44783758  1.287819e+00
## 794   0.04995319 0.4252584 -0.77095772  8.820595e-01
## 795  -1.87495162 0.4824594 -2.88217907 -9.272404e-01
## 796  -1.42344479 0.4745458 -2.39237379 -5.475636e-01
## 797  -1.42693331 0.4608529 -2.34218733 -5.595504e-01
## 798  -0.83283137 0.4226613 -1.69301502 -1.725150e-02
## 799   1.44383385 0.4891654  0.51285339  2.455144e+00
## 800  -0.84664011 0.4297948 -1.71863556 -1.416219e-02
## 801  -1.64607335 0.4685655 -2.60417141 -7.681328e-01
## 802  -3.22002867 0.6967839 -4.70792459 -1.958689e+00
## 803  -1.02057485 0.4318923 -1.88705047 -2.199853e-01
## 804  -1.43264193 0.4759969 -2.38721484 -5.615225e-01
## 805  -1.02096777 0.4371918 -1.89468639 -1.743639e-01
## 806  -0.48034624 0.4249714 -1.30568380  3.590071e-01
## 807   0.05137448 0.4196841 -0.76987272  8.749415e-01
## 808   0.59422614 0.4524922 -0.26327991  1.493348e+00
## 809  -2.14531571 0.5304067 -3.24631247 -1.155208e+00
## 810  -0.13049364 0.4147541 -0.91867817  6.879644e-01
## 811  -1.87912837 0.5044413 -2.88410747 -9.662015e-01
## 812  -0.84398901 0.4324937 -1.71215431 -2.615325e-02
## 813  -1.43114053 0.4664262 -2.35807311 -5.255731e-01
## 814  -0.83239237 0.4295209 -1.69576200  9.545832e-03
## 815  -2.13517342 0.5262513 -3.24686991 -1.171303e+00
## 816   0.40757115 0.4258122 -0.41742136  1.268224e+00
## 817   0.05156391 0.4322826 -0.78275299  9.023105e-01
## 818  -1.21613083 0.4458441 -2.14109677 -3.648019e-01
## 819  -3.23195041 0.7234675 -4.79356054 -1.947549e+00
## 820  -1.87179638 0.4918165 -2.85833006 -9.570871e-01
## 821  -2.80020520 0.6385424 -4.15610439 -1.663304e+00
## 822  -2.77742364 0.5943258 -4.05695083 -1.682719e+00
## 823  -1.89071896 0.4922255 -2.88937314 -9.520374e-01
## 824  -1.87719665 0.5060260 -2.90782737 -9.247771e-01
## 825  -1.87026477 0.5082180 -2.91340158 -9.216632e-01
## 826  -0.30913465 0.4269490 -1.12279961  5.153518e-01
## 827  -2.79094097 0.5941861 -4.06123819 -1.717323e+00
## 828  -1.22822225 0.4511725 -2.13501225 -3.741163e-01
## 829  -1.02123720 0.4305773 -1.87070966 -1.865764e-01
## 830  -1.22621419 0.4548892 -2.15089517 -3.749338e-01
## 831  -1.02681603 0.4374550 -1.94130808 -2.373038e-01
## 832  -1.44113421 0.4719718 -2.40158313 -5.299352e-01
## 833   0.79459165 0.4457427 -0.09435037  1.697770e+00
## 834   1.69857894 0.5103598  0.72482369  2.766139e+00
## 835   0.05118938 0.4059426 -0.73477863  8.358316e-01
## 836   0.40746651 0.4285235 -0.44326189  1.269447e+00
## 837  -1.01977248 0.4405153 -1.89291810 -1.525919e-01
## 838   1.44229159 0.4878802  0.54065006  2.430528e+00
## 839   0.22394649 0.4113753 -0.56043630  1.050349e+00
## 840   1.69282747 0.5265905  0.74066719  2.789780e+00
## 841   0.99328950 0.4474348  0.14048480  1.896463e+00
## 842   0.58312172 0.4221102 -0.22916931  1.438402e+00
## 843   0.22698583 0.4168843 -0.58752805  1.073970e+00
## 844  -0.48046027 0.4104745 -1.28870808  3.140589e-01
## 845   1.00734684 0.4787749  0.08250753  1.980898e+00
## 846   0.22112777 0.4109379 -0.57142538  1.006650e+00
## 847  -1.20908333 0.4297136 -2.05409574 -4.011359e-01
## 848   1.70062406 0.5196483  0.71493149  2.750889e+00
## 849  -3.22527792 0.7022941 -4.73571688 -1.976449e+00
## 850   0.40979394 0.4288141 -0.43204996  1.258633e+00
## 851  -0.29882849 0.4174198 -1.08089948  5.386492e-01
## 852   0.06130880 0.4388103 -0.77149488  9.208190e-01
## 853  -1.02434301 0.4372377 -1.89437180 -1.677692e-01
## 854  -0.12713726 0.4110258 -0.90383981  6.726942e-01
## 855  -1.43386606 0.4655494 -2.37668755 -5.431325e-01
## 856  -1.21375860 0.4556898 -2.13786292 -3.478444e-01
## 857  -2.78661811 0.6123781 -4.10248864 -1.696089e+00
## 858  -1.02174386 0.4434576 -1.93214397 -1.678692e-01
## 859  -0.47288039 0.4217475 -1.28315808  3.585715e-01
## 860  -0.47691630 0.4313894 -1.32837317  3.761593e-01
## 861  -1.64172717 0.4785678 -2.61745821 -7.464399e-01
## 862  -1.02530684 0.4337357 -1.87105356 -1.898322e-01
## 863   0.23387370 0.4314214 -0.60393629  1.097754e+00
## 864  -1.02617194 0.4380154 -1.89167315 -1.830695e-01
## 865   0.58697991 0.4433650 -0.26436020  1.485338e+00
## 866   0.05822742 0.4268022 -0.77090581  8.935302e-01
## 867   0.78205883 0.4459674 -0.07408247  1.693928e+00
## 868   1.22088183 0.4809190  0.31305488  2.217160e+00
## 869  -0.63997308 0.4393719 -1.50683553  2.467653e-01
## 870  -0.12299989 0.4087695 -0.91350451  6.680873e-01
## 871  -0.29920066 0.4051027 -1.09070886  5.071973e-01
## 872   0.23012673 0.4300899 -0.58930560  1.090269e+00
## 873  -1.63572725 0.4822011 -2.63451157 -7.076269e-01
## 874  -2.13504002 0.5277636 -3.23647254 -1.160966e+00
## 875  -1.87925172 0.4909877 -2.84749883 -9.642433e-01
## 876   0.40446851 0.4305002 -0.43845963  1.275879e+00
## 877  -1.20611669 0.4363590 -2.09723860 -3.646782e-01
## 878  -1.01927180 0.4455500 -1.91728783 -1.724017e-01
## 879  -0.84033218 0.4199970 -1.67226063 -1.997837e-02
## 880   0.05350069 0.4343738 -0.77833364  9.073431e-01
## 881  -1.42743874 0.4545418 -2.35226230 -5.420684e-01
## 882  -1.87659471 0.5128454 -2.93219499 -9.191748e-01
## 883   0.40882160 0.4238629 -0.39795184  1.237974e+00
## 884   0.58660330 0.4296777 -0.23940168  1.459036e+00
## 885  -0.66495053 0.4381994 -1.52582530  2.104510e-01
## 886  -1.64870825 0.4920805 -2.64388424 -7.252999e-01
## 887   1.21706544 0.4757811  0.33107311  2.196025e+00
## 888  -0.47950692 0.4384128 -1.39387262  3.633398e-01
## 889  -0.13155665 0.4316751 -0.97178951  7.111907e-01
## 890  -0.48507190 0.4208992 -1.31719547  3.561830e-01
## 891  -1.22498370 0.4575929 -2.11429890 -3.593018e-01
## 892  -0.48483911 0.4412932 -1.38575325  3.772862e-01
## 893  -0.64495423 0.4201107 -1.48098981  1.748773e-01
## 894  -0.30618510 0.4228462 -1.13436961  5.127733e-01
## 895   0.79187908 0.4528580 -0.06686921  1.693437e+00
## 896   0.40621031 0.4357628 -0.43701654  1.253582e+00
## 897  -2.14924222 0.5383010 -3.25822849 -1.150523e+00
## 898  -1.42675435 0.4567170 -2.36550380 -5.720945e-01
## 899  -0.65474027 0.4106756 -1.46918060  1.303954e-01
## 900   1.97736631 0.5535751  0.94848823  3.071672e+00
## 901  -1.22423343 0.4403594 -2.12762695 -3.900730e-01
## 902   0.41341695 0.4306562 -0.41172761  1.257481e+00
## 903  -1.03035575 0.4489965 -1.92305775 -1.372675e-01
## 904  -0.83689782 0.4201371 -1.68253065 -1.164341e-02
## 905  -1.42253348 0.4492491 -2.33957606 -5.774981e-01
## 906   0.60692221 0.4413440 -0.23534825  1.484210e+00
## 907   1.20601448 0.4570801  0.35819779  2.146547e+00
## 908   1.71103053 0.5223023  0.73975455  2.763342e+00
## 909   1.98358090 0.5425064  0.98020181  3.066144e+00
## 910   0.78989693 0.4495626 -0.06203640  1.644969e+00
## 911   1.21122784 0.4752654  0.31896186  2.166381e+00
## 912   0.05027282 0.4193054 -0.76700901  8.544628e-01
## 913  -1.64102284 0.4802894 -2.62917168 -7.384456e-01
## 914  -1.22808837 0.4461772 -2.11490994 -3.919656e-01
## 915  -1.43868595 0.4571905 -2.36657520 -5.641768e-01
## 916  -0.48134680 0.4299126 -1.33300944  3.822074e-01
## 917   0.05065820 0.4161170 -0.76158668  8.670457e-01
## 918   1.43699813 0.5026312  0.51244394  2.475378e+00
## 919   0.78043618 0.4435975 -0.06911461  1.684072e+00
## 920  -0.12807195 0.4212337 -0.93406513  7.092060e-01
## 921   1.46038688 0.5188192  0.49006277  2.567453e+00
## 922  -0.65118244 0.4314821 -1.51583006  2.134476e-01
## 923  -0.83227178 0.4308425 -1.66939400  1.836852e-02
## 924   0.05567286 0.4317017 -0.79211841  9.232811e-01
## 925  -2.13201745 0.5275270 -3.20942516 -1.143238e+00
## 926   0.99134600 0.4572970  0.11028696  1.898332e+00
## 927   0.59412874 0.4415976 -0.24894774  1.460347e+00
## 928   0.79400334 0.4476520 -0.05415934  1.701425e+00
## 929   0.79839955 0.4532159 -0.08093120  1.696368e+00
## 930   0.23147864 0.4137614 -0.55879472  1.065216e+00
## 931  -1.42615715 0.4679567 -2.36989514 -5.496176e-01
## 932   0.41201646 0.4328467 -0.42347697  1.243708e+00
## 933  -1.64966537 0.4966358 -2.64753440 -6.962280e-01
## 934  -0.30078775 0.4410450 -1.15236633  5.604554e-01
## 935  -1.88749590 0.4932334 -2.88768162 -9.688579e-01
## 936  -1.88234943 0.4920212 -2.88352390 -9.572380e-01
## 937  -1.02088521 0.4363210 -1.89603329 -1.718425e-01
## 938  -0.84486564 0.4232872 -1.70972858 -6.571348e-02
## 939  -1.42507000 0.4539823 -2.33059671 -5.732010e-01
## 940  -0.83060591 0.4380072 -1.69216613  1.408398e-02
## 941  -0.30801358 0.4294108 -1.14707486  5.363116e-01
## 942   0.05163672 0.4100202 -0.73072556  8.603765e-01
## 943  -0.30388664 0.4182628 -1.13029079  5.303154e-01
## 944   0.40580141 0.4456497 -0.44284340  1.287220e+00
## 945   0.04225958 0.4199566 -0.76998847  8.561453e-01
## 946   0.22609219 0.4318985 -0.61913772  1.090303e+00
## 947  -3.20686738 0.7105497 -4.70579177 -1.918319e+00
## 948   0.78610127 0.4633218 -0.12155038  1.716389e+00
## 949   1.20848691 0.4880388  0.24957518  2.222786e+00
## 950   1.21490456 0.4722795  0.32562246  2.148827e+00
## 951   1.00553702 0.4609970  0.14070689  1.943650e+00
## 952  -0.66619377 0.4204516 -1.49293652  1.441662e-01
## 953  -0.13005018 0.4274838 -0.97978235  7.034851e-01
## 954   0.99647173 0.4497564  0.13984190  1.886529e+00
## 955   0.23222459 0.4312563 -0.60049276  1.097144e+00
## 956  -2.16247275 0.5495156 -3.30519682 -1.147517e+00
## 957  -2.45097623 0.5641846 -3.59834333 -1.444458e+00
## 958  -1.02251534 0.4396289 -1.89333772 -1.817399e-01
## 959  -1.43564389 0.4618083 -2.40369159 -5.731161e-01
## 960  -0.47961203 0.4217910 -1.30067203  3.437551e-01
## 961  -1.42143712 0.4569849 -2.35225068 -5.447469e-01
## 962  -0.85076516 0.4404195 -1.73435738 -1.329945e-02
## 963   0.23246925 0.4376796 -0.63028793  1.100607e+00
## 964   1.97895506 0.5514318  0.95757673  3.124831e+00
## 965   1.00564113 0.4551914  0.14677973  1.912042e+00
## 966   0.99920752 0.4648443  0.12131264  1.903210e+00
## 967   0.98624085 0.4536941  0.10260681  1.907072e+00
## 968   0.04849497 0.4188586 -0.76179405  8.717779e-01
## 969   0.99610449 0.4533720  0.14102825  1.919086e+00
## 970   1.00139012 0.4630331  0.11766646  1.923547e+00
## 971  -0.84139402 0.4361004 -1.72502387 -1.978589e-02
## 972  -0.30315359 0.4151909 -1.10199243  5.224065e-01
## 973   0.41104192 0.4322761 -0.41586859  1.259390e+00
## 974   1.21846511 0.4745328  0.30630744  2.168915e+00
## 975  -1.42026024 0.4588309 -2.35128841 -5.491277e-01
## 976   0.40657055 0.4390366 -0.44853386  1.282077e+00
## 977   0.05290146 0.4269867 -0.74600529  9.000768e-01
## 978  -0.65450068 0.4251751 -1.51569521  1.792372e-01
## 979  -0.30923932 0.4235316 -1.14957417  5.358137e-01
## 980  -0.12585952 0.4170527 -0.94148460  6.982148e-01
## 981   1.21027744 0.4650433  0.30218998  2.162969e+00
## 982   0.41288175 0.4519592 -0.46362053  1.320963e+00
## 983  -0.28978400 0.4080427 -1.07048039  5.080007e-01
## 984  -0.49018399 0.4333481 -1.34248244  3.634741e-01
## 985  -0.66220352 0.4244079 -1.48668491  1.484484e-01
## 986  -0.29523347 0.4271922 -1.11892631  5.508178e-01
## 987  -1.64378756 0.4890997 -2.63574451 -7.268991e-01
## 988  -1.22159127 0.4563014 -2.13200848 -3.598227e-01
## 989  -1.02571205 0.4388117 -1.90489018 -1.801677e-01
## 990   1.97914899 0.5364087  0.98603925  3.091331e+00
## 991   0.60134158 0.4434710 -0.27355651  1.484138e+00
## 992  -0.48895415 0.4150532 -1.31498014  3.286416e-01
## 993   0.04425267 0.4313596 -0.78073039  8.989311e-01
## 994   1.00304343 0.4558372  0.14399519  1.925770e+00
## 995  -1.65164327 0.4858428 -2.66162484 -7.291912e-01
## 996  -1.64972385 0.4897483 -2.65807934 -7.284504e-01
## 997  -0.83428035 0.4377027 -1.72085336 -1.386650e-02
## 998   0.40769277 0.4370891 -0.42986216  1.273147e+00
## 999   0.59227261 0.4398192 -0.25721886  1.447935e+00
## 1000  0.04351597 0.4266012 -0.80548979  8.894334e-01
## 1001 -0.13017712 0.4334486 -0.97803418  7.334917e-01
## 1002  1.45058335 0.4917103  0.52775919  2.445863e+00
## 1003  1.21294131 0.4705315  0.32191946  2.154118e+00
## 1004  0.78853659 0.4571980 -0.10952354  1.711710e+00
## 1005 -1.88388870 0.5052946 -2.93220590 -9.609528e-01
## 1006 -2.13542931 0.5205871 -3.21861084 -1.158773e+00
## 1007 -0.30522382 0.4389936 -1.15611971  5.575267e-01
## 1008 -2.15089970 0.5338278 -3.22153634 -1.175643e+00
## 1009 -2.45892853 0.5800554 -3.67821975 -1.428937e+00
## 1010 -1.87558948 0.5069358 -2.94960294 -9.317278e-01
## 1011  1.44766525 0.4959894  0.51993244  2.456687e+00
## 1012 -0.65516057 0.4283956 -1.49708801  1.828319e-01
## 1013 -0.29362328 0.4224685 -1.10326976  5.554761e-01
## 1014 -0.13102825 0.4170178 -0.97066073  6.725169e-01
## 1015 -0.83266367 0.4279445 -1.65683737 -1.334469e-02
## 1016 -0.84629814 0.4326577 -1.69718378 -3.318095e-02
## 1017  0.79434068 0.4446659 -0.05548205  1.666344e+00
## 1018  0.05170848 0.4358085 -0.78436592  9.075003e-01
## 1019 -0.48469624 0.4135659 -1.31112340  2.991684e-01
## 1020 -1.02000003 0.4361044 -1.89650070 -1.829372e-01
## 1021  1.00022744 0.4602700  0.11088821  1.931885e+00
## 1022 -0.13175618 0.4365659 -1.00187778  7.301598e-01
## 1023  0.41676559 0.4187769 -0.40659788  1.236953e+00
## 1024  0.04706047 0.4322626 -0.82098517  9.109948e-01
## 1025  0.59307625 0.4303624 -0.23718983  1.439292e+00
## 1026  0.77883288 0.4455927 -0.07963697  1.664599e+00
## 1027  0.60585309 0.4324711 -0.21923407  1.472469e+00
## 1028  1.70623271 0.5205581  0.74961448  2.778079e+00
## 1029  1.21834462 0.4738495  0.32306421  2.194164e+00
## 1030  0.79480063 0.4514684 -0.06183413  1.694776e+00
## 1031  0.22283842 0.4345059 -0.61330796  1.090416e+00
## 1032  0.99067096 0.4532333  0.13361833  1.907405e+00
## 1033  0.60259544 0.4379739 -0.24395238  1.465057e+00
## 1034  1.20313553 0.4626437  0.32942595  2.192653e+00
## 1035  1.68854440 0.5168788  0.71598515  2.770415e+00
## 1036 -0.83967760 0.4139782 -1.67511351 -5.425284e-02
## 1037 -0.11414118 0.4290324 -0.98344991  7.252289e-01
## 1038  0.41393859 0.4218960 -0.39934978  1.264303e+00
## 1039 -0.66047158 0.4245400 -1.48447314  1.591288e-01
## 1040 -0.64930521 0.4169523 -1.47753083  1.646996e-01
## 1041  1.20298728 0.4662947  0.31698408  2.129846e+00
## 1042  1.97978985 0.5410642  0.97470605  3.102250e+00
## 1043  0.99209699 0.4554358  0.11152723  1.904439e+00
## 1044  1.71050393 0.5300166  0.71855475  2.793036e+00
## 1045  1.98097233 0.5338344  0.99777314  3.095965e+00
## 1046  0.41526117 0.4292421 -0.39777280  1.291174e+00
## 1047  1.45424008 0.4990472  0.52815738  2.487980e+00
## 1048  0.04604476 0.4217521 -0.78452067  9.090589e-01
## 1049  1.45352098 0.4971734  0.53455066  2.440044e+00
## 1050  3.10453996 0.6975961  1.84176439  4.572022e+00
## 1051  2.67287575 0.6346516  1.53422888  3.970778e+00
## 1052  1.97630654 0.5592587  0.96827555  3.134931e+00
## 1053  1.98043374 0.5572150  0.93111171  3.134036e+00
## 1054  1.44839708 0.4934104  0.50547031  2.457419e+00
## 1055  0.04915386 0.4227713 -0.79169027  8.971742e-01
## 1056  0.22226701 0.4203083 -0.59931327  1.073592e+00
## 1057  0.59692109 0.4412397 -0.22529218  1.464302e+00
## 1058  1.21208857 0.4826808  0.31244573  2.170827e+00
## 1059  1.70596567 0.5131116  0.75089375  2.756368e+00
## 1060 -0.13129112 0.4153994 -0.95060768  6.815438e-01
## 1061  0.78826901 0.4442776 -0.07585408  1.690682e+00
## 1062 -1.89284870 0.5009138 -2.91139338 -9.712107e-01
## 1063 -2.43153486 0.5794878 -3.60110638 -1.361582e+00
## 1064 -3.22054850 0.7000607 -4.71482956 -1.998683e+00
## 1065  0.59987674 0.4413647 -0.25225785  1.499710e+00
## 1066  2.30521719 0.5925177  1.19782139  3.536442e+00
## 1067  0.22333883 0.4182218 -0.58419757  1.069695e+00
## 1068  1.71010345 0.5199039  0.74737972  2.786508e+00
## 1069 -0.85296166 0.4275054 -1.70173232 -2.442826e-02
## 1070 -0.48803070 0.4127872 -1.29379181  3.314370e-01
## 1071  0.41442663 0.4287218 -0.42911814  1.272433e+00
## 1072  2.29959899 0.5878392  1.20136215  3.541600e+00
## 1073  1.20696978 0.4702705  0.28001572  2.156712e+00
## 1074  1.21913447 0.4910883  0.28161729  2.235583e+00
## 1075  0.99838847 0.4549759  0.11099236  1.943196e+00
## 1076  1.70481216 0.5101353  0.75749989  2.780738e+00
## 1077  1.22290663 0.4799747  0.30623566  2.193178e+00
## 1078 -0.30338231 0.4232869 -1.15738686  5.362177e-01
## 1079  1.44534464 0.5046884  0.51131045  2.465625e+00
## 1080  1.21080397 0.4769314  0.33992073  2.135494e+00
## 1081  0.58902410 0.4412558 -0.25456977  1.460254e+00
## 1082  0.99921656 0.4757785  0.09555629  1.972798e+00
## 1083  0.42186786 0.4369449 -0.42110793  1.286200e+00
## 1084 -0.82663621 0.4281414 -1.67470213 -2.872992e-03
## 1085 -0.83716285 0.4280256 -1.69959358 -2.068806e-02
## 1086 -0.65870730 0.4203587 -1.49339494  1.484657e-01
## 1087 -0.12203133 0.4391319 -0.95305400  7.509778e-01
## 1088 -1.63227882 0.4733726 -2.65168132 -7.244617e-01
## 1089  1.45288336 0.4889553  0.54521738  2.463032e+00
## 1090  0.98943048 0.4645522  0.09981998  1.920633e+00
## 1091  1.20865261 0.4717886  0.32671221  2.178657e+00
## 1092  0.22562158 0.4277574 -0.59651846  1.096077e+00
## 1093  1.45380121 0.4893025  0.53262833  2.448931e+00
## 1094  0.79260424 0.4416945 -0.05712052  1.694844e+00
## 1095 -0.12307994 0.4226737 -0.96442383  7.073865e-01
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#posterior predictive check}
\FunctionTok{pp\_check}\NormalTok{(modelo\_2pl)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Using 10 posterior draws for ppc type 'dens_overlay' by default.
\end{verbatim}

\includegraphics{Sin-título_files/figure-latex/unnamed-chunk-3-1.pdf}

Resultados:

Los estadísticos de convergencia (Rhat = 1.00) y las muestras efectivas
(ESS \textgreater{} 700 en todos los parámetros) indican que el muestreo
posterior fue adecuado.Además, las comprobaciones predictivas
posteriores (pp\_check) muestran una excelente correspondencia entre las
respuestas observadas y las simuladas por el modelo. Por otro lado, se
estimó la habilidad de 1095 estudaintes (θ), con media 0 y desviación
típica 1.29. Además, la dificultad de 26 ítems tuvo un rango de -2.67
(más facil) y +1.28 (más dificil).

Ejemplo:

ítem R088Q04T, con b -2.67 e intervalo del 95\% {[}−3.14, −2.17{]}.

Respecto a la comprobación predictiva posterior, Se utilizó la función
pp\_check() para evaluar el ajuste del modelo. El gráfico de densidades
muestra que las respuestas simuladas desde la posterior (líneas claras)
coinciden con la distribución de las respuestas reales (línea oscura).
Esto respalda la adecuación del modelo 1PL a los datos observados.

En conclusión, el enfoque bayesiano aplicado al modelo 1PL de la Teoría
de Respuesta al ítem, ha permitido obtener estimaciones de habilidad y
dificultad, junto con intervalos creíbles que cuantifican la
incertidumbre de forma clara. La evaluación predictiva posterior sugiere
un buen ajuste del modelo, lo que refuerza su utilidad para analizar
ítems de comprensión lectora en evaluaciones educativas como PISA.

\end{document}
